## Preliminaries

In [1]:
from os.path import abspath
from subprocess import run

import meeko
import molscrub
import prody
import pandas as pd
from rdkit import Chem

from src.utils.prep import ligand_prep

In [2]:
CWD = abspath(".")

In [3]:
nat_lig = pd.read_csv(
        "../data/antibiotics_pubchem_query.csv", index_col=0
    )
mir_lig = pd.read_csv("../data/mirror_ligand.csv", index_col=0)

In [4]:
nat_lig.head()

,amoxicillin,piperacillin,ticarcillin,cefepime,cefazolin,ceftolozane,ceftriaxone,ceftazidime,aztreonam,imipenem,...,linezolid,amikacin,tobramycin,streptomycin,kanamycin,trimethoprim,sulfamethoxazole,ciprofloxacin,levofloxacin,Moxifloxacin
cid,33613,43672,36921,5479537,33255,53234134,5479530,5481173,5742832,104838,...,441401,37768,36294,19649,6032,5578,5329,2764,149096,152946
smiles,CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H]...,CCN1CCN(C(=O)C1=O)C(=O)N[C@H](C2=CC=CC=C2)C(=O...,CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H]...,C[N+]1(CCCC1)CC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)...,CC1=NN=C(S1)SCC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)...,CC(C)(C(=O)O)O/N=C(/C1=NSC(=N1)N)\C(=O)N[C@H]2...,CN1C(=NC(=O)C(=O)N1)SCC2=C(N3[C@@H]([C@@H](C3=...,CC(C)(C(=O)O)O/N=C(/C1=CSC(=N1)N)\C(=O)N[C@H]2...,C[C@H]1[C@@H](C(=O)N1S(=O)(=O)O)NC(=O)/C(=N\OC...,C[C@H]([C@@H]1[C@H]2CC(=C(N2C1=O)C(=O)O)SCCN=CN)O,...,CC(=O)NC[C@H]1CN(C(=O)O1)C2=CC(=C(C=C2)N3CCOCC3)F,C1[C@@H]([C@H]([C@@H]([C@H]([C@@H]1NC(=O)[C@H]...,C1[C@@H]([C@H]([C@@H]([C@H]([C@@H]1N)O[C@@H]2[...,C[C@H]1[C@@]([C@H]([C@@H](O1)O[C@@H]2[C@H]([C@...,C1[C@H]([C@@H]([C@H]([C@@H]([C@H]1N)O[C@@H]2[C...,COC1=CC(=CC(=C1OC)OC)CC2=CN=C(N=C2N)N,CC1=CC(=NO1)NS(=O)(=O)C2=CC=C(C=C2)N,C1CC1N2C=C(C(=O)C3=CC(=C(C=C32)N4CCNCC4)F)C(=O)O,C[C@H]1COC2=C3N1C=C(C(=O)C3=CC(=C2N4CCN(CC4)C)...,COC1=C2C(=CC(=C1N3C[C@@H]4CCCN[C@@H]4C3)F)C(=O...
inchi,InChI=1S/C16H19N3O5S/c1-16(2)11(15(23)24)19-13...,InChI=1S/C23H27N5O7S/c1-4-26-10-11-27(19(32)18...,InChI=1S/C15H16N2O6S2/c1-15(2)9(14(22)23)17-11...,InChI=1S/C19H24N6O5S2/c1-25(5-3-4-6-25)7-10-8-...,InChI=1S/C14H14N8O4S3/c1-6-17-18-14(29-6)28-4-...,"InChI=1S/C23H30N12O8S2/c1-23(2,20(40)41)43-31-...",InChI=1S/C18H18N8O7S3/c1-25-18(22-12(28)13(29)...,"InChI=1S/C22H22N6O7S2/c1-22(2,20(33)34)35-26-1...","InChI=1S/C13H17N5O8S2/c1-5-7(10(20)18(5)28(23,...",InChI=1S/C12H17N3O4S/c1-6(16)9-7-4-8(20-3-2-14...,...,InChI=1S/C16H20FN3O4/c1-11(21)18-9-13-10-20(16...,InChI=1S/C22H43N5O13/c23-2-1-8(29)20(36)27-7-3...,InChI=1S/C18H37N5O9/c19-3-9-8(25)2-7(22)17(29-...,"InChI=1S/C21H39N7O12/c1-5-21(36,4-30)16(40-17-...",InChI=1S/C18H36N4O11/c19-2-6-10(25)12(27)13(28...,InChI=1S/C14H18N4O3/c1-19-10-5-8(6-11(20-2)12(...,InChI=1S/C10H11N3O3S/c1-7-6-10(12-16-7)13-17(1...,InChI=1S/C17H18FN3O3/c18-13-7-11-14(8-15(13)20...,InChI=1S/C18H20FN3O4/c1-10-9-26-17-14-11(16(23...,InChI=1S/C21H24FN3O4/c1-29-20-17-13(19(26)14(2...
coordinate_type,2d,2d,2d,2d,2d,2d,2d,2d,2d,2d,...,2d,2d,2d,2d,2d,2d,2d,2d,2d,2d
xlogp,-2,0.5,0.8,-0.1,-0.4,-3.2,-1.3,0.4,0.3,-0.7,...,0.7,-7.9,-6.2,-8,-6.9,0.9,0.9,-1.1,-0.4,0.6

In [5]:
mir_lig.head()

,amoxicillin,piperacillin,ticarcillin,cefepime,cefazolin,ceftolozane,ceftriaxone,ceftazidime,aztreonam,imipenem,...,linezolid,amikacin,tobramycin,streptomycin,kanamycin,trimethoprim,sulfamethoxazole,ciprofloxacin,levofloxacin,Moxifloxacin
cid,33613,43672,36921,5479537,33255,53234134,5479530,5481173,5742832,104838,...,441401,37768,36294,19649,6032,5578,5329,2764,149096,152946
smiles,CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H]...,CCN1CCN(C(=O)C1=O)C(=O)N[C@H](C2=CC=CC=C2)C(=O...,CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H]...,C[N+]1(CCCC1)CC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)...,CC1=NN=C(S1)SCC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)...,CC(C)(C(=O)O)O/N=C(/C1=NSC(=N1)N)\C(=O)N[C@H]2...,CN1C(=NC(=O)C(=O)N1)SCC2=C(N3[C@@H]([C@@H](C3=...,CC(C)(C(=O)O)O/N=C(/C1=CSC(=N1)N)\C(=O)N[C@H]2...,C[C@H]1[C@@H](C(=O)N1S(=O)(=O)O)NC(=O)/C(=N\OC...,C[C@H]([C@@H]1[C@H]2CC(=C(N2C1=O)C(=O)O)SCCN=CN)O,...,CC(=O)NC[C@H]1CN(C(=O)O1)C2=CC(=C(C=C2)N3CCOCC3)F,C1[C@@H]([C@H]([C@@H]([C@H]([C@@H]1NC(=O)[C@H]...,C1[C@@H]([C@H]([C@@H]([C@H]([C@@H]1N)O[C@@H]2[...,C[C@H]1[C@@]([C@H]([C@@H](O1)O[C@@H]2[C@H]([C@...,C1[C@H]([C@@H]([C@H]([C@@H]([C@H]1N)O[C@@H]2[C...,COC1=CC(=CC(=C1OC)OC)CC2=CN=C(N=C2N)N,CC1=CC(=NO1)NS(=O)(=O)C2=CC=C(C=C2)N,C1CC1N2C=C(C(=O)C3=CC(=C(C=C32)N4CCNCC4)F)C(=O)O,C[C@H]1COC2=C3N1C=C(C(=O)C3=CC(=C2N4CCN(CC4)C)...,COC1=C2C(=CC(=C1N3C[C@@H]4CCCN[C@@H]4C3)F)C(=O...
inchi,InChI=1S/C16H19N3O5S/c1-16(2)11(15(23)24)19-13...,InChI=1S/C23H27N5O7S/c1-4-26-10-11-27(19(32)18...,InChI=1S/C15H16N2O6S2/c1-15(2)9(14(22)23)17-11...,InChI=1S/C19H24N6O5S2/c1-25(5-3-4-6-25)7-10-8-...,InChI=1S/C14H14N8O4S3/c1-6-17-18-14(29-6)28-4-...,"InChI=1S/C23H30N12O8S2/c1-23(2,20(40)41)43-31-...",InChI=1S/C18H18N8O7S3/c1-25-18(22-12(28)13(29)...,"InChI=1S/C22H22N6O7S2/c1-22(2,20(33)34)35-26-1...","InChI=1S/C13H17N5O8S2/c1-5-7(10(20)18(5)28(23,...",InChI=1S/C12H17N3O4S/c1-6(16)9-7-4-8(20-3-2-14...,...,InChI=1S/C16H20FN3O4/c1-11(21)18-9-13-10-20(16...,InChI=1S/C22H43N5O13/c23-2-1-8(29)20(36)27-7-3...,InChI=1S/C18H37N5O9/c19-3-9-8(25)2-7(22)17(29-...,"InChI=1S/C21H39N7O12/c1-5-21(36,4-30)16(40-17-...",InChI=1S/C18H36N4O11/c19-2-6-10(25)12(27)13(28...,InChI=1S/C14H18N4O3/c1-19-10-5-8(6-11(20-2)12(...,InChI=1S/C10H11N3O3S/c1-7-6-10(12-16-7)13-17(1...,InChI=1S/C17H18FN3O3/c18-13-7-11-14(8-15(13)20...,InChI=1S/C18H20FN3O4/c1-10-9-26-17-14-11(16(23...,InChI=1S/C21H24FN3O4/c1-29-20-17-13(19(26)14(2...
coordinate_type,2d,2d,2d,2d,2d,2d,2d,2d,2d,2d,...,2d,2d,2d,2d,2d,2d,2d,2d,2d,2d
mirror_smi,CC1(C)S[C@H]2[C@@H](NC(=O)[C@@H](N)c3ccc(O)cc3...,CCN1CCN(C(=O)N[C@H](C(=O)N[C@H]2C(=O)N3[C@H]2S...,CC1(C)S[C@H]2[C@@H](NC(=O)[C@@H](C(=O)O)c3ccsc...,CO/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)[O-])=C(C[N+...,Cc1nnc(SCC2=C(C(=O)O)N3C(=O)[C@H](NC(=O)Cn4cnn...,Cn1c(N)c(NC(=O)NCCN)c[n+]1CC1=C(C(=O)[O-])N2C(...,CO/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)O)=C(CSc3nc(...,CC(C)(O/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)[O-])=C...,C[C@@H]1[C@@H](NC(=O)/C(=N\OC(C)(C)C(=O)O)c2cs...,C[C@H](O)[C@@H]1C(=O)N2C(C(=O)O)=C(SCCN=CN)C[C...,...,CC(=O)NC[C@@H]1CN(c2ccc(N3CCOCC3)c(F)c2)C(=O)O1,NCC[C@@H](O)C(=O)N[C@H]1C[C@@H](N)[C@H](O[C@@H...,NC[C@@H]1O[C@@H](O[C@@H]2[C@@H](O)[C@H](O[C@@H...,CN[C@H]1[C@@H](O[C@@H]2[C@@H](O[C@@H]3[C@@H](O...,NC[C@@H]1O[C@@H](O[C@@H]2[C@@H](O)[C@H](O[C@@H...,COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC,Cc1cc(NS(=O)(=O)c2ccc(N)cc2)no1,O=C(O)c1cn(C2CC2)c2cc(N3CCNCC3)c(F)cc2c1=O,C[C@@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O...,COc1c(N2C[C@H]3CCCN[C@H]3C2)c(F)cc2c(=O)c(C(=O...

## Ligand Preparation

In [ ]:
#* Performed successfully 4:52:24 AM for 8m 0.9s
# for lg, ml in zip(nat_lig, mir_lig):
#     lg_name: str = f"Native {lg.title()}"
#     ml_name: str = f"Mirror {ml.title()}"
#
#     lg_smi: str = nat_lig[lg]["smiles"]
#     ml_smi: str = mir_lig[ml]["mirror_smi"]
#     ligand_prep(
#         lg_smi, lg_name, f"{CWD}/../data/ligand_prep"
#     )
#     ligand_prep(
#         ml_smi, ml_name, f"{CWD}/../data/ligand_prep"
#     )

Scrubing Native Amoxicillin with scrub.py CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H](C3=CC=C(C=C3)O)N)C(=O)O)C -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Amoxicillin.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native Amoxicillin with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Amoxicillin.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Amoxicillin.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror Amoxicillin with scrub.py CC1(C)S[C@H]2[C@@H](NC(=O)[C@@H](N)c3ccc(O)cc3)C(=O)N2[C@@H]1C(=O)O -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Amoxicillin.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror Amoxicillin with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Amoxicillin.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Amoxicillin.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native Piperacillin with scrub.py CCN1CCN(C(=O)C1=O)C(=O)N[C@H](C2=CC=CC=C2)C(=O)N[C@H]3[C@@H]4N(C3=O)[C@H](C(S4)(C)C)C(=O)O -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Piperacillin.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native Piperacillin with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Piperacillin.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Piperacillin.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror Piperacillin with scrub.py CCN1CCN(C(=O)N[C@H](C(=O)N[C@H]2C(=O)N3[C@H]2SC(C)(C)[C@H]3C(=O)O)c2ccccc2)C(=O)C1=O -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Piperacillin.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror Piperacillin with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Piperacillin.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Piperacillin.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native Ticarcillin with scrub.py CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H](C3=CSC=C3)C(=O)O)C(=O)O)C -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Ticarcillin.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native Ticarcillin with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Ticarcillin.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Ticarcillin.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror Ticarcillin with scrub.py CC1(C)S[C@H]2[C@@H](NC(=O)[C@@H](C(=O)O)c3ccsc3)C(=O)N2[C@@H]1C(=O)O -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Ticarcillin.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror Ticarcillin with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Ticarcillin.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Ticarcillin.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native Cefepime with scrub.py C[N+]1(CCCC1)CC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)/C(=N\OC)/C4=CSC(=N4)N)SC2)C(=O)[O-] -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Cefepime.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native Cefepime with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Cefepime.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Cefepime.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror Cefepime with scrub.py CO/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)[O-])=C(C[N+]3(C)CCCC3)CS[C@@H]12)c1csc(N)n1 -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Cefepime.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror Cefepime with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Cefepime.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Cefepime.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native Cefazolin with scrub.py CC1=NN=C(S1)SCC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)CN4C=NN=N4)SC2)C(=O)O -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Cefazolin.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native Cefazolin with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Cefazolin.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Cefazolin.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror Cefazolin with scrub.py Cc1nnc(SCC2=C(C(=O)O)N3C(=O)[C@H](NC(=O)Cn4cnnn4)[C@@H]3SC2)s1 -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Cefazolin.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror Cefazolin with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Cefazolin.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Cefazolin.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native Ceftolozane with scrub.py CC(C)(C(=O)O)O/N=C(/C1=NSC(=N1)N)\C(=O)N[C@H]2[C@@H]3N(C2=O)C(=C(CS3)C[N+]4=CC(=C(N4C)N)NC(=O)NCCN)C(=O)[O-] -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Ceftolozane.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native Ceftolozane with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Ceftolozane.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Ceftolozane.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror Ceftolozane with scrub.py Cn1c(N)c(NC(=O)NCCN)c[n+]1CC1=C(C(=O)[O-])N2C(=O)[C@H](NC(=O)/C(=N\OC(C)(C)C(=O)O)c3nsc(N)n3)[C@@H]2SC1 -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Ceftolozane.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror Ceftolozane with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Ceftolozane.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Ceftolozane.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native Ceftriaxone with scrub.py CN1C(=NC(=O)C(=O)N1)SCC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)/C(=N\OC)/C4=CSC(=N4)N)SC2)C(=O)O -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Ceftriaxone.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native Ceftriaxone with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Ceftriaxone.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Ceftriaxone.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror Ceftriaxone with scrub.py CO/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)O)=C(CSc3nc(=O)c(=O)[nH]n3C)CS[C@@H]12)c1csc(N)n1 -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Ceftriaxone.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror Ceftriaxone with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Ceftriaxone.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Ceftriaxone.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native Ceftazidime with scrub.py CC(C)(C(=O)O)O/N=C(/C1=CSC(=N1)N)\C(=O)N[C@H]2[C@@H]3N(C2=O)C(=C(CS3)C[N+]4=CC=CC=C4)C(=O)[O-] -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Ceftazidime.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native Ceftazidime with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Ceftazidime.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Ceftazidime.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror Ceftazidime with scrub.py CC(C)(O/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)[O-])=C(C[n+]3ccccc3)CS[C@@H]12)c1csc(N)n1)C(=O)O -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Ceftazidime.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror Ceftazidime with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Ceftazidime.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Ceftazidime.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native Aztreonam with scrub.py C[C@H]1[C@@H](C(=O)N1S(=O)(=O)O)NC(=O)/C(=N\OC(C)(C)C(=O)O)/C2=CSC(=N2)N -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Aztreonam.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native Aztreonam with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Aztreonam.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Aztreonam.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror Aztreonam with scrub.py C[C@@H]1[C@@H](NC(=O)/C(=N\OC(C)(C)C(=O)O)c2csc(N)n2)C(=O)N1S(=O)(=O)O -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Aztreonam.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror Aztreonam with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Aztreonam.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Aztreonam.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native Imipenem with scrub.py C[C@H]([C@@H]1[C@H]2CC(=C(N2C1=O)C(=O)O)SCCN=CN)O -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Imipenem.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native Imipenem with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Imipenem.sdf -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Native Imipenem.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror Imipenem with scrub.py C[C@H](O)[C@@H]1C(=O)N2C(C(=O)O)=C(SCCN=CN)C[C@@H]12 -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/ligand_prep/Mirror Imipenem.sdf --ph 7.0 --skip_tautomer --skip_acidbase
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0

## Target Preparation

In [6]:
target_info: dict[str, str] = {
        "6I1H": "MER",
        "5M18": "MUR",
        "8CF1": "TAC",
        "8CGD": "AM2",
        "3FL9": "TOP",
        "1TX2": "680",
        "4DUH": "RLI",
        "5IQB": "GNP"
    }

In [7]:
receptor_info: dict = {}

In [11]:
def receptor_atoms(pdb_token: str, path: str, outfile: str):
    atoms_from_pdb = prody.parsePDB(f"{path}/{pdb_token}.pdb")
    receptor_selection = "chain A and not water and not hetero"
    receptor_atoms = atoms_from_pdb.select(receptor_selection)
    prody_receptorPDB = f"{outfile}/{pdb_token}_receptor_atoms.pdb"
    prody.writePDB(prody_receptorPDB, receptor_atoms)
    return prody_receptorPDB


def prep_receptor(pdb_token: str, path: str, ligand: str, outfile: str, rc_hash: dict, mirror: bool):
    atoms_from_pdb = prody.parsePDB(f"{path}/{pdb_token}.pdb")
    ligand_selection = f"chain A and resname {ligand}"
    ligand_atoms = atoms_from_pdb.select(ligand_selection)
    center_x, center_y, center_z = prody.calcCenter(ligand_atoms)
    center = [center_x, center_y, center_z]

    if mirror:
        prody_ligandPDB = f"{outfile}/L-{ligand}.pdb"
    else:
        prody_ligandPDB = f"{outfile}/{ligand}.pdb"

    prody.writePDB(prody_ligandPDB, ligand_atoms)


    size_x = 20.0
    size_y = 20.0
    size_z = 20.0
    size = [size_x, size_y, size_z]

    rc_hash[pdb_token] = {
            "size": size,
            "center": center
        }

    file_name = f"{outfile}/{pdb_token}_prep"
    prody_receptorPDB = receptor_atoms(pdb_token, path, outfile)
    mkpreprecep: list = [
            "mk_prepare_receptor.py",
            "-i", f"{prody_receptorPDB}",
            "-o", f"{file_name}",
            "-p", "--write_pdb", f"{file_name}.pdb",
            "-v", "--box_center",
            str(center_x), str(center_y), str(center_z),
            "--box_size", str(size_x), str(size_y), str(size_z),
            "--allow_bad_res",
            "--default_altloc"
        ]
    print(" ".join(mkpreprecep))
    run(mkpreprecep)

In [ ]:
#! this is a test code
# prep_receptor(
#     "6I1H".lower(),
#     f"../data/targets",
#     "MER",
#     f"{CWD}/../data/receptor_prep"
# )

@> 5241 atoms and 1 coordinate set(s) were parsed in 0.03s.
@> 5241 atoms and 1 coordinate set(s) were parsed in 0.04s.

mk_prepare_receptor.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/receptor_prep/6i1h_receptor_atoms.pdb -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/receptor_prep/6i1h_prep -p --write_pdb /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/receptor_prep/6i1h_prep.pdb -v --box_center -5.978153846153846 -52.50296153846154 38.259846153846155 --box_size 20.0 20.0 20.0

@> 2519 atoms and 1 coordinate set(s) were parsed in 0.01s.

Files written:
    /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/receptor_prep/6i1h_prep.pdb <-- processed receptor PDB
  /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/receptor_prep/6i1h_prep.pdbqt <-- static (i.e., rigid) receptor input file
/var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/receptor_prep/6i1h_prep.box.txt <-- Vina-style box dimension file
/var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/receptor_prep/6i1h_prep.box.pdb <-- PDB file to visualize the grid box

In [ ]:
#! this is a test code
# prep_receptor(
#     f"L-{'6I1H'.lower()}",
#     f"../data/mirror_targets",
#     "MER",
#     f"{CWD}/../data/receptor_prep"
# )

@> 5241 atoms and 1 coordinate set(s) were parsed in 0.02s.
@> 5241 atoms and 1 coordinate set(s) were parsed in 0.02s.

mk_prepare_receptor.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/receptor_prep/L-6i1h_receptor_atoms.pdb -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/receptor_prep/L-6i1h_prep -p --write_pdb /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/receptor_prep/L-6i1h_prep.pdb -v --box_center 5.978153846153846 52.50296153846154 -38.259846153846155 --box_size 20.0 20.0 20.0

@> 2519 atoms and 1 coordinate set(s) were parsed in 0.01s.

Files written:
    /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/receptor_prep/L-6i1h_prep.pdb <-- processed receptor PDB
  /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/receptor_prep/L-6i1h_prep.pdbqt <-- static (i.e., rigid) receptor input file
/var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/receptor_prep/L-6i1h_prep.box.txt <-- Vina-style box dimension file
/var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/receptor_prep/L-6i1h_prep.box.pdb <-- PDB file to visualize the grid box

In [13]:
for rc, lg in target_info.items():
    prep_receptor(
        rc.lower(),
        f"{CWD}/../data/targets",
        lg,
        f"{CWD}/../data/native_target_prep",
        receptor_info,
        False
    )
    prep_receptor(
        f"L-{rc.lower()}",
        f"{CWD}/../data/mirror_targets",
        lg,
        f"{CWD}/../data/mirror_target_prep",
        receptor_info,
        True
    )

@> 5241 atoms and 1 coordinate set(s) were parsed in 0.02s.
@> 5241 atoms and 1 coordinate set(s) were parsed in 0.02s.

mk_prepare_receptor.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/native_target_prep/6i1h_receptor_atoms.pdb -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/native_target_prep/6i1h_prep -p --write_pdb /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/native_target_prep/6i1h_prep.pdb -v --box_center -5.978153846153846 -52.50296153846154 38.259846153846155 --box_size 20.0 20.0 20.0 --allow_bad_res --default_altloc

mk_prepare_receptor.py: error: argument --default_altloc: expected one argument
@> 5241 atoms and 1 coordinate set(s) were parsed in 0.02s.
@> 5241 atoms and 1 coordinate set(s) were parsed in 0.02s.

usage: mk_prepare_receptor.py [-h] [--read_pdb PDB_FILENAME]
                              [--read_pqr PQR_FILENAME] [-i MACROMOL_FILENAME]
                              [-o OUTPUT_BASENAME] [-p [PDBQT_FILENAME ...]]
                              [-j [JSON_FILENAME ...]]
                              [--write_pdb [PDB_FILENAME ...]]
                              [-g [GPF_FILENAME ...]]
                              [-v [VINA_BOX_FILENAME ...]]
                              [--debug_fn DEBUG_FN] [-n SET_TEMPLATE]
                              [-d DELETE_RESIDUES] [-b BLUNT_ENDS]
                              [--add_templates ADD_TEMPLATES]
                              [--cache_templates [CACHE_TEMPLATES]]
                              [--mk_config JSON_FILENAME] [-a]
                              [--default_altloc DEFAULT_ALTLOC]
                              [--wanted_altloc WANTED_ALTLOC] [-f FLEXRES]
                              [-t ROT_TERMINAL_GROUP]
                              [--charge_model {gasteiger,espaloma,zero,read}]
                              [--box_size X Y Z] [--box_center X Y Z]
                              [--box_center_off_reactive_res]
                              [--box_enveloping FILENAME] [--padding PADDING]
                              [-r REACTIVE_FLEXRES]
                              [--reactive_name REACTIVE_NAME]
                              [-s REACTIVE_NAME_SPECIFIC] [--r_eq_12 R_EQ_12]
                              [--eps_12 EPS_12]
                              [--r_eq_13_scaling R_EQ_13_SCALING]
                              [--r_eq_14_scaling R_EQ_14_SCALING]

options:
  -h, --help            show this help message and exit

Input/Output:
  --read_pdb PDB_FILENAME
                        reads PDB, not PDBQT, and does not use ProDy
  --read_pqr PQR_FILENAME
                        reads PQR and does not use ProDy
  -i MACROMOL_FILENAME, --read_with_prody MACROMOL_FILENAME
                        reads PDB/mmCIF file with Prody
  -o OUTPUT_BASENAME, --output_basename OUTPUT_BASENAME
                        default basename for --write options used without
                        filename
  -p [PDBQT_FILENAME ...], --write_pdbqt [PDBQT_FILENAME ...]
                        adds _rigid/_flex with flexible residues (filename
                        defaults to --output_basename when not specified)
  -j [JSON_FILENAME ...], --write_json [JSON_FILENAME ...]
                        parameterized receptor (filename defaults to
                        --output_basename when not specified)
  --write_pdb [PDB_FILENAME ...]
                        prepared receptor (must specify filename)
  -g [GPF_FILENAME ...], --write_gpf [GPF_FILENAME ...]
                        autogrid input file (filename defaults to
                        --output_basename when not specified)
  -v [VINA_BOX_FILENAME ...], --write_vina_box [VINA_BOX_FILENAME ...]
                        config file for Vina with box dimensions (filename
                        defaults to --output_basename when not specified_
  --debug_fn DEBUG_FN   log debug level to filename

Receptor perception:
  -n SET_TEMPLATE, --set_template SET_TEMPLATE
                        e.g. A:5,7=CYX,B:17=HID
  -d DELETE_RESIDUES, --delete_residues DELETE_RESIDUES
                        e.g. A:350,B:15,16,17
  -b BLUNT_ENDS, --blunt_ends BLUNT_ENDS
                        e.g. A:123,200=2,A:1=0
  --add_templates ADD_TEMPLATES
                        Additional residue templates. Can be a JSON file path
                        or 'resname:file.sdf'.
  --cache_templates [CACHE_TEMPLATES]
                        Turns on caching of ResidueChemTemplates (default is
                        OFF) by this option and (optionally) a provided JSON
                        filename. Default cache filename is:
                        $HOME/.meeko_residue_chem_templates_cached.json) When
                        the caching is ON, the templates for polymer
                        construction will be read from the specified cache
                        file and updates may be made to the same file in a
                        cumulative manner.
  --mk_config JSON_FILENAME
                        [.json]
  -a, --allow_bad_res   delete residues with missing atoms instead of raising
                        error
  --default_altloc DEFAULT_ALTLOC
                        default alternate location (overridden by
                        --wanted_altloc)
  --wanted_altloc WANTED_ALTLOC
                        require altloc for specific residues, e.g. :5=B,B:17=A
  -f FLEXRES, --flexres FLEXRES
                        specify the flexible residues by the chain ID and
                        residue number, e.g. -f ":42,B:23" is equivalent to -f
                        ":42" -f "B:23" (leave chain ID empty if omitted in
                        input PDB or mmCIF)
  -t ROT_TERMINAL_GROUP, --rot_terminal_group ROT_TERMINAL_GROUP
                        specify the residues for which to make terminal
                        functional group rotatable by the chain ID and residue
                        number, e.g. -t ":42,B:23" is equivalent to -t ":42"
                        -t "B:23" (leave chain ID empty if omitted in input
                        PDB or mmCIF)
  --charge_model {gasteiger,espaloma,zero,read}
                        default is gasteiger, 'zero' sets all zeros, 'read'
                        requires --read_pqr

Size and center of grid box:
  --box_size X Y Z      size of grid box (x, y, z) in Angstrom
  --box_center X Y Z    center of grid box (x, y, z) in Angstrom
  --box_center_off_reactive_res
                        project grid box center along CA-CB bond 5 A away from
                        CB (only applicable when there is exactly one reactive
                        flexible residue)
  --box_enveloping FILENAME
                        Box will envelop atoms in this file [.sdf .mol .mol2
                        .pdb .pdbqt]
  --padding PADDING     padding around atoms passed to --box_enveloping [A]

Reactive:
  -r REACTIVE_FLEXRES, --reactive_flexres REACTIVE_FLEXRES
                        same as --flexres but for reactive residues (max 8)
  --reactive_name REACTIVE_NAME
                        set name of reactive atom of a residue type, e.g:
                        --reactive_name 'TRP:NE1'. Repeat flag for multiple
                        assignments. Overridden by --reactive_name_specific
  -s REACTIVE_NAME_SPECIFIC, --reactive_name_specific REACTIVE_NAME_SPECIFIC
                        set name of reactive atom for an individual residue by
                        the residue ID, e.g: -s 'A:42=NE2'. Residue will be
                        reactive.
  --r_eq_12 R_EQ_12     r_eq for reactive atoms (1-2 interaction)
  --eps_12 EPS_12       epsilon for reactive atoms (1-2 interaction)
  --r_eq_13_scaling R_EQ_13_SCALING
                        r_eq scaling for 1-3 interaction across reactive atoms
  --r_eq_14_scaling R_EQ_14_SCALING
                        r_eq scaling for 1-4 interaction across reactive atoms
mk_prepare_receptor.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/mirror_target_prep/L-6i1h_receptor_atoms.pdb -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/mirror_target_prep/L-6i1h_prep -p --write_pdb /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/mirror_target_prep/L-6i1h_prep.pdb -v --box_center 5.978153846153846 52.50296153846154 -38.259846153846155 --box_size 20.0 20.0 20.0 --allow_bad_res --default_altloc

mk_prepare_receptor.py: error: argument --default_altloc: expected one argument
@> 10684 atoms and 1 coordinate set(s) were parsed in 0.05s.

usage: mk_prepare_receptor.py [-h] [--read_pdb PDB_FILENAME]
                              [--read_pqr PQR_FILENAME] [-i MACROMOL_FILENAME]
                              [-o OUTPUT_BASENAME] [-p [PDBQT_FILENAME ...]]
                              [-j [JSON_FILENAME ...]]
                              [--write_pdb [PDB_FILENAME ...]]
                              [-g [GPF_FILENAME ...]]
                              [-v [VINA_BOX_FILENAME ...]]
                              [--debug_fn DEBUG_FN] [-n SET_TEMPLATE]
                              [-d DELETE_RESIDUES] [-b BLUNT_ENDS]
                              [--add_templates ADD_TEMPLATES]
                              [--cache_templates [CACHE_TEMPLATES]]
                              [--mk_config JSON_FILENAME] [-a]
                              [--default_altloc DEFAULT_ALTLOC]
                              [--wanted_altloc WANTED_ALTLOC] [-f FLEXRES]
                              [-t ROT_TERMINAL_GROUP]
                              [--charge_model {gasteiger,espaloma,zero,read}]
                              [--box_size X Y Z] [--box_center X Y Z]
                              [--box_center_off_reactive_res]
                              [--box_enveloping FILENAME] [--padding PADDING]
                              [-r REACTIVE_FLEXRES]
                              [--reactive_name REACTIVE_NAME]
                              [-s REACTIVE_NAME_SPECIFIC] [--r_eq_12 R_EQ_12]
                              [--eps_12 EPS_12]
                              [--r_eq_13_scaling R_EQ_13_SCALING]
                              [--r_eq_14_scaling R_EQ_14_SCALING]

options:
  -h, --help            show this help message and exit

Input/Output:
  --read_pdb PDB_FILENAME
                        reads PDB, not PDBQT, and does not use ProDy
  --read_pqr PQR_FILENAME
                        reads PQR and does not use ProDy
  -i MACROMOL_FILENAME, --read_with_prody MACROMOL_FILENAME
                        reads PDB/mmCIF file with Prody
  -o OUTPUT_BASENAME, --output_basename OUTPUT_BASENAME
                        default basename for --write options used without
                        filename
  -p [PDBQT_FILENAME ...], --write_pdbqt [PDBQT_FILENAME ...]
                        adds _rigid/_flex with flexible residues (filename
                        defaults to --output_basename when not specified)
  -j [JSON_FILENAME ...], --write_json [JSON_FILENAME ...]
                        parameterized receptor (filename defaults to
                        --output_basename when not specified)
  --write_pdb [PDB_FILENAME ...]
                        prepared receptor (must specify filename)
  -g [GPF_FILENAME ...], --write_gpf [GPF_FILENAME ...]
                        autogrid input file (filename defaults to
                        --output_basename when not specified)
  -v [VINA_BOX_FILENAME ...], --write_vina_box [VINA_BOX_FILENAME ...]
                        config file for Vina with box dimensions (filename
                        defaults to --output_basename when not specified_
  --debug_fn DEBUG_FN   log debug level to filename

Receptor perception:
  -n SET_TEMPLATE, --set_template SET_TEMPLATE
                        e.g. A:5,7=CYX,B:17=HID
  -d DELETE_RESIDUES, --delete_residues DELETE_RESIDUES
                        e.g. A:350,B:15,16,17
  -b BLUNT_ENDS, --blunt_ends BLUNT_ENDS
                        e.g. A:123,200=2,A:1=0
  --add_templates ADD_TEMPLATES
                        Additional residue templates. Can be a JSON file path
                        or 'resname:file.sdf'.
  --cache_templates [CACHE_TEMPLATES]
                        Turns on caching of ResidueChemTemplates (default is
                        OFF) by this option and (optionally) a provided JSON
                        filename. Default cache filename is:
                        $HOME/.meeko_residue_chem_templates_cached.json) When
                        the caching is ON, the templates for polymer
                        construction will be read from the specified cache
                        file and updates may be made to the same file in a
                        cumulative manner.
  --mk_config JSON_FILENAME
                        [.json]
  -a, --allow_bad_res   delete residues with missing atoms instead of raising
                        error
  --default_altloc DEFAULT_ALTLOC
                        default alternate location (overridden by
                        --wanted_altloc)
  --wanted_altloc WANTED_ALTLOC
                        require altloc for specific residues, e.g. :5=B,B:17=A
  -f FLEXRES, --flexres FLEXRES
                        specify the flexible residues by the chain ID and
                        residue number, e.g. -f ":42,B:23" is equivalent to -f
                        ":42" -f "B:23" (leave chain ID empty if omitted in
                        input PDB or mmCIF)
  -t ROT_TERMINAL_GROUP, --rot_terminal_group ROT_TERMINAL_GROUP
                        specify the residues for which to make terminal
                        functional group rotatable by the chain ID and residue
                        number, e.g. -t ":42,B:23" is equivalent to -t ":42"
                        -t "B:23" (leave chain ID empty if omitted in input
                        PDB or mmCIF)
  --charge_model {gasteiger,espaloma,zero,read}
                        default is gasteiger, 'zero' sets all zeros, 'read'
                        requires --read_pqr

Size and center of grid box:
  --box_size X Y Z      size of grid box (x, y, z) in Angstrom
  --box_center X Y Z    center of grid box (x, y, z) in Angstrom
  --box_center_off_reactive_res
                        project grid box center along CA-CB bond 5 A away from
                        CB (only applicable when there is exactly one reactive
                        flexible residue)
  --box_enveloping FILENAME
                        Box will envelop atoms in this file [.sdf .mol .mol2
                        .pdb .pdbqt]
  --padding PADDING     padding around atoms passed to --box_enveloping [A]

Reactive:
  -r REACTIVE_FLEXRES, --reactive_flexres REACTIVE_FLEXRES
                        same as --flexres but for reactive residues (max 8)
  --reactive_name REACTIVE_NAME
                        set name of reactive atom of a residue type, e.g:
                        --reactive_name 'TRP:NE1'. Repeat flag for multiple
                        assignments. Overridden by --reactive_name_specific
  -s REACTIVE_NAME_SPECIFIC, --reactive_name_specific REACTIVE_NAME_SPECIFIC
                        set name of reactive atom for an individual residue by
                        the residue ID, e.g: -s 'A:42=NE2'. Residue will be
                        reactive.
  --r_eq_12 R_EQ_12     r_eq for reactive atoms (1-2 interaction)
  --eps_12 EPS_12       epsilon for reactive atoms (1-2 interaction)
  --r_eq_13_scaling R_EQ_13_SCALING
                        r_eq scaling for 1-3 interaction across reactive atoms
  --r_eq_14_scaling R_EQ_14_SCALING
                        r_eq scaling for 1-4 interaction across reactive atoms

@> 10684 atoms and 1 coordinate set(s) were parsed in 0.05s.

mk_prepare_receptor.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/native_target_prep/5m18_receptor_atoms.pdb -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/native_target_prep/5m18_prep -p --write_pdb /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/native_target_prep/5m18_prep.pdb -v --box_center 19.421823529411764 -18.162411764705883 -52.577411764705886 --box_size 20.0 20.0 20.0 --allow_bad_res --default_altloc
usage: mk_prepare_receptor.py [-h] [--read_pdb PDB_FILENAME]
                              [--read_pqr PQR_FILENAME] [-i MACROMOL_FILENAME]
                              [-o OUTPUT_BASENAME] [-p [PDBQT_FILENAME ...]]
                              [-j [JSON_FILENAME ...]]
                              [--write_pdb [PDB_FILENAME ...]]
                              [-g [GPF_FILENAME ...]]
                              [-v [VINA_BOX_FILENAME ...]]
                              [--debug_fn DEBUG_FN] [-n SET_TEMPLATE]
                              [-d DELETE_RESIDUES] [-b BLUNT_ENDS]
                              [--add_templates ADD_TEMPLATES]
                              [--cache_templates [CACHE_TEMPLATES]]
                              [--mk_config JSON_FILENAME] [-a]
                              [--default_altloc DEFAULT_ALTLOC]
                              [--wanted_altloc WANTED_ALTLOC] [-f FLEXRES]
                              [-t ROT_TERMINAL_GROUP]
                              [--charge_model {gasteiger,espaloma,zero,read}]
                              [--box_size X Y Z] [--box_center X Y Z]
                              [--box_center_off_reactive_res]
                              [--box_enveloping FILENAME] [--padding PADDING]
                              [-r REACTIVE_FLEXRES]
                              [--reactive_name REACTIVE_NAME]
                              [-s REACTIVE_NAME_SPECIFIC] [--r_eq_12 R_EQ_12]
                              [--eps_12 EPS_12]
                              [--r_eq_13_scaling R_EQ_13_SCALING]
                              [--r_eq_14_scaling R_EQ_14_SCALING]

options:
  -h, --help            show this help message and exit

Input/Output:
  --read_pdb PDB_FILENAME
                        reads PDB, not PDBQT, and does not use ProDy
  --read_pqr PQR_FILENAME
                        reads PQR and does not use ProDy
  -i MACROMOL_FILENAME, --read_with_prody MACROMOL_FILENAME
                        reads PDB/mmCIF file with Prody
  -o OUTPUT_BASENAME, --output_basename OUTPUT_BASENAME
                        default basename for --write options used without
                        filename
  -p [PDBQT_FILENAME ...], --write_pdbqt [PDBQT_FILENAME ...]
                        adds _rigid/_flex with flexible residues (filename
                        defaults to --output_basename when not specified)
  -j [JSON_FILENAME ...], --write_json [JSON_FILENAME ...]
                        parameterized receptor (filename defaults to
                        --output_basename when not specified)
  --write_pdb [PDB_FILENAME ...]
                        prepared receptor (must specify filename)
  -g [GPF_FILENAME ...], --write_gpf [GPF_FILENAME ...]
                        autogrid input file (filename defaults to
                        --output_basename when not specified)
  -v [VINA_BOX_FILENAME ...], --write_vina_box [VINA_BOX_FILENAME ...]
                        config file for Vina with box dimensions (filename
                        defaults to --output_basename when not specified_
  --debug_fn DEBUG_FN   log debug level to filename

Receptor perception:
  -n SET_TEMPLATE, --set_template SET_TEMPLATE
                        e.g. A:5,7=CYX,B:17=HID
  -d DELETE_RESIDUES, --delete_residues DELETE_RESIDUES
                        e.g. A:350,B:15,16,17
  -b BLUNT_ENDS, --blunt_ends BLUNT_ENDS
                        e.g. A:123,200=2,A:1=0
  --add_templates ADD_TEMPLATES
                        Additional residue templates. Can be a JSON file path
                        or 'resname:file.sdf'.
  --cache_templates [CACHE_TEMPLATES]
                        Turns on caching of ResidueChemTemplates (default is
                        OFF) by this option and (optionally) a provided JSON
                        filename. Default cache filename is:
                        $HOME/.meeko_residue_chem_templates_cached.json) When
                        the caching is ON, the templates for polymer
                        construction will be read from the specified cache
                        file and updates may be made to the same file in a
                        cumulative manner.
  --mk_config JSON_FILENAME
                        [.json]
  -a, --allow_bad_res   delete residues with missing atoms instead of raising
                        error
  --default_altloc DEFAULT_ALTLOC
                        default alternate location (overridden by
                        --wanted_altloc)
  --wanted_altloc WANTED_ALTLOC
                        require altloc for specific residues, e.g. :5=B,B:17=A
  -f FLEXRES, --flexres FLEXRES
                        specify the flexible residues by the chain ID and
                        residue number, e.g. -f ":42,B:23" is equivalent to -f
                        ":42" -f "B:23" (leave chain ID empty if omitted in
                        input PDB or mmCIF)
  -t ROT_TERMINAL_GROUP, --rot_terminal_group ROT_TERMINAL_GROUP
                        specify the residues for which to make terminal
                        functional group rotatable by the chain ID and residue
                        number, e.g. -t ":42,B:23" is equivalent to -t ":42"
                        -t "B:23" (leave chain ID empty if omitted in input
                        PDB or mmCIF)
  --charge_model {gasteiger,espaloma,zero,read}
                        default is gasteiger, 'zero' sets all zeros, 'read'
                        requires --read_pqr

Size and center of grid box:
  --box_size X Y Z      size of grid box (x, y, z) in Angstrom
  --box_center X Y Z    center of grid box (x, y, z) in Angstrom
  --box_center_off_reactive_res
                        project grid box center along CA-CB bond 5 A away from
                        CB (only applicable when there is exactly one reactive
                        flexible residue)
  --box_enveloping FILENAME
                        Box will envelop atoms in this file [.sdf .mol .mol2
                        .pdb .pdbqt]
  --padding PADDING     padding around atoms passed to --box_enveloping [A]

Reactive:
  -r REACTIVE_FLEXRES, --reactive_flexres REACTIVE_FLEXRES
                        same as --flexres but for reactive residues (max 8)
  --reactive_name REACTIVE_NAME
                        set name of reactive atom of a residue type, e.g:
                        --reactive_name 'TRP:NE1'. Repeat flag for multiple
                        assignments. Overridden by --reactive_name_specific
  -s REACTIVE_NAME_SPECIFIC, --reactive_name_specific REACTIVE_NAME_SPECIFIC
                        set name of reactive atom for an individual residue by
                        the residue ID, e.g: -s 'A:42=NE2'. Residue will be
                        reactive.
  --r_eq_12 R_EQ_12     r_eq for reactive atoms (1-2 interaction)
  --eps_12 EPS_12       epsilon for reactive atoms (1-2 interaction)
  --r_eq_13_scaling R_EQ_13_SCALING
                        r_eq scaling for 1-3 interaction across reactive atoms
  --r_eq_14_scaling R_EQ_14_SCALING
                        r_eq scaling for 1-4 interaction across reactive atoms

mk_prepare_receptor.py: error: argument --default_altloc: expected one argument
@> 10684 atoms and 1 coordinate set(s) were parsed in 0.06s.
@> 10684 atoms and 1 coordinate set(s) were parsed in 0.05s.

mk_prepare_receptor.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/mirror_target_prep/L-5m18_receptor_atoms.pdb -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/mirror_target_prep/L-5m18_prep -p --write_pdb /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/mirror_target_prep/L-5m18_prep.pdb -v --box_center -19.421823529411764 18.162411764705883 52.577411764705886 --box_size 20.0 20.0 20.0 --allow_bad_res --default_altloc

mk_prepare_receptor.py: error: argument --default_altloc: expected one argument
@> 18957 atoms and 1 coordinate set(s) were parsed in 0.06s.

usage: mk_prepare_receptor.py [-h] [--read_pdb PDB_FILENAME]
                              [--read_pqr PQR_FILENAME] [-i MACROMOL_FILENAME]
                              [-o OUTPUT_BASENAME] [-p [PDBQT_FILENAME ...]]
                              [-j [JSON_FILENAME ...]]
                              [--write_pdb [PDB_FILENAME ...]]
                              [-g [GPF_FILENAME ...]]
                              [-v [VINA_BOX_FILENAME ...]]
                              [--debug_fn DEBUG_FN] [-n SET_TEMPLATE]
                              [-d DELETE_RESIDUES] [-b BLUNT_ENDS]
                              [--add_templates ADD_TEMPLATES]
                              [--cache_templates [CACHE_TEMPLATES]]
                              [--mk_config JSON_FILENAME] [-a]
                              [--default_altloc DEFAULT_ALTLOC]
                              [--wanted_altloc WANTED_ALTLOC] [-f FLEXRES]
                              [-t ROT_TERMINAL_GROUP]
                              [--charge_model {gasteiger,espaloma,zero,read}]
                              [--box_size X Y Z] [--box_center X Y Z]
                              [--box_center_off_reactive_res]
                              [--box_enveloping FILENAME] [--padding PADDING]
                              [-r REACTIVE_FLEXRES]
                              [--reactive_name REACTIVE_NAME]
                              [-s REACTIVE_NAME_SPECIFIC] [--r_eq_12 R_EQ_12]
                              [--eps_12 EPS_12]
                              [--r_eq_13_scaling R_EQ_13_SCALING]
                              [--r_eq_14_scaling R_EQ_14_SCALING]

options:
  -h, --help            show this help message and exit

Input/Output:
  --read_pdb PDB_FILENAME
                        reads PDB, not PDBQT, and does not use ProDy
  --read_pqr PQR_FILENAME
                        reads PQR and does not use ProDy
  -i MACROMOL_FILENAME, --read_with_prody MACROMOL_FILENAME
                        reads PDB/mmCIF file with Prody
  -o OUTPUT_BASENAME, --output_basename OUTPUT_BASENAME
                        default basename for --write options used without
                        filename
  -p [PDBQT_FILENAME ...], --write_pdbqt [PDBQT_FILENAME ...]
                        adds _rigid/_flex with flexible residues (filename
                        defaults to --output_basename when not specified)
  -j [JSON_FILENAME ...], --write_json [JSON_FILENAME ...]
                        parameterized receptor (filename defaults to
                        --output_basename when not specified)
  --write_pdb [PDB_FILENAME ...]
                        prepared receptor (must specify filename)
  -g [GPF_FILENAME ...], --write_gpf [GPF_FILENAME ...]
                        autogrid input file (filename defaults to
                        --output_basename when not specified)
  -v [VINA_BOX_FILENAME ...], --write_vina_box [VINA_BOX_FILENAME ...]
                        config file for Vina with box dimensions (filename
                        defaults to --output_basename when not specified_
  --debug_fn DEBUG_FN   log debug level to filename

Receptor perception:
  -n SET_TEMPLATE, --set_template SET_TEMPLATE
                        e.g. A:5,7=CYX,B:17=HID
  -d DELETE_RESIDUES, --delete_residues DELETE_RESIDUES
                        e.g. A:350,B:15,16,17
  -b BLUNT_ENDS, --blunt_ends BLUNT_ENDS
                        e.g. A:123,200=2,A:1=0
  --add_templates ADD_TEMPLATES
                        Additional residue templates. Can be a JSON file path
                        or 'resname:file.sdf'.
  --cache_templates [CACHE_TEMPLATES]
                        Turns on caching of ResidueChemTemplates (default is
                        OFF) by this option and (optionally) a provided JSON
                        filename. Default cache filename is:
                        $HOME/.meeko_residue_chem_templates_cached.json) When
                        the caching is ON, the templates for polymer
                        construction will be read from the specified cache
                        file and updates may be made to the same file in a
                        cumulative manner.
  --mk_config JSON_FILENAME
                        [.json]
  -a, --allow_bad_res   delete residues with missing atoms instead of raising
                        error
  --default_altloc DEFAULT_ALTLOC
                        default alternate location (overridden by
                        --wanted_altloc)
  --wanted_altloc WANTED_ALTLOC
                        require altloc for specific residues, e.g. :5=B,B:17=A
  -f FLEXRES, --flexres FLEXRES
                        specify the flexible residues by the chain ID and
                        residue number, e.g. -f ":42,B:23" is equivalent to -f
                        ":42" -f "B:23" (leave chain ID empty if omitted in
                        input PDB or mmCIF)
  -t ROT_TERMINAL_GROUP, --rot_terminal_group ROT_TERMINAL_GROUP
                        specify the residues for which to make terminal
                        functional group rotatable by the chain ID and residue
                        number, e.g. -t ":42,B:23" is equivalent to -t ":42"
                        -t "B:23" (leave chain ID empty if omitted in input
                        PDB or mmCIF)
  --charge_model {gasteiger,espaloma,zero,read}
                        default is gasteiger, 'zero' sets all zeros, 'read'
                        requires --read_pqr

Size and center of grid box:
  --box_size X Y Z      size of grid box (x, y, z) in Angstrom
  --box_center X Y Z    center of grid box (x, y, z) in Angstrom
  --box_center_off_reactive_res
                        project grid box center along CA-CB bond 5 A away from
                        CB (only applicable when there is exactly one reactive
                        flexible residue)
  --box_enveloping FILENAME
                        Box will envelop atoms in this file [.sdf .mol .mol2
                        .pdb .pdbqt]
  --padding PADDING     padding around atoms passed to --box_enveloping [A]

Reactive:
  -r REACTIVE_FLEXRES, --reactive_flexres REACTIVE_FLEXRES
                        same as --flexres but for reactive residues (max 8)
  --reactive_name REACTIVE_NAME
                        set name of reactive atom of a residue type, e.g:
                        --reactive_name 'TRP:NE1'. Repeat flag for multiple
                        assignments. Overridden by --reactive_name_specific
  -s REACTIVE_NAME_SPECIFIC, --reactive_name_specific REACTIVE_NAME_SPECIFIC
                        set name of reactive atom for an individual residue by
                        the residue ID, e.g: -s 'A:42=NE2'. Residue will be
                        reactive.
  --r_eq_12 R_EQ_12     r_eq for reactive atoms (1-2 interaction)
  --eps_12 EPS_12       epsilon for reactive atoms (1-2 interaction)
  --r_eq_13_scaling R_EQ_13_SCALING
                        r_eq scaling for 1-3 interaction across reactive atoms
  --r_eq_14_scaling R_EQ_14_SCALING
                        r_eq scaling for 1-4 interaction across reactive atoms

@> 18957 atoms and 1 coordinate set(s) were parsed in 0.06s.

mk_prepare_receptor.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/native_target_prep/8cf1_receptor_atoms.pdb -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/native_target_prep/8cf1_prep -p --write_pdb /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/native_target_prep/8cf1_prep.pdb -v --box_center 248.1948125 311.26956249999995 211.46221874999995 --box_size 20.0 20.0 20.0 --allow_bad_res --default_altloc

mk_prepare_receptor.py: error: argument --default_altloc: expected one argument
@> 18957 atoms and 1 coordinate set(s) were parsed in 0.07s.

usage: mk_prepare_receptor.py [-h] [--read_pdb PDB_FILENAME]
                              [--read_pqr PQR_FILENAME] [-i MACROMOL_FILENAME]
                              [-o OUTPUT_BASENAME] [-p [PDBQT_FILENAME ...]]
                              [-j [JSON_FILENAME ...]]
                              [--write_pdb [PDB_FILENAME ...]]
                              [-g [GPF_FILENAME ...]]
                              [-v [VINA_BOX_FILENAME ...]]
                              [--debug_fn DEBUG_FN] [-n SET_TEMPLATE]
                              [-d DELETE_RESIDUES] [-b BLUNT_ENDS]
                              [--add_templates ADD_TEMPLATES]
                              [--cache_templates [CACHE_TEMPLATES]]
                              [--mk_config JSON_FILENAME] [-a]
                              [--default_altloc DEFAULT_ALTLOC]
                              [--wanted_altloc WANTED_ALTLOC] [-f FLEXRES]
                              [-t ROT_TERMINAL_GROUP]
                              [--charge_model {gasteiger,espaloma,zero,read}]
                              [--box_size X Y Z] [--box_center X Y Z]
                              [--box_center_off_reactive_res]
                              [--box_enveloping FILENAME] [--padding PADDING]
                              [-r REACTIVE_FLEXRES]
                              [--reactive_name REACTIVE_NAME]
                              [-s REACTIVE_NAME_SPECIFIC] [--r_eq_12 R_EQ_12]
                              [--eps_12 EPS_12]
                              [--r_eq_13_scaling R_EQ_13_SCALING]
                              [--r_eq_14_scaling R_EQ_14_SCALING]

options:
  -h, --help            show this help message and exit

Input/Output:
  --read_pdb PDB_FILENAME
                        reads PDB, not PDBQT, and does not use ProDy
  --read_pqr PQR_FILENAME
                        reads PQR and does not use ProDy
  -i MACROMOL_FILENAME, --read_with_prody MACROMOL_FILENAME
                        reads PDB/mmCIF file with Prody
  -o OUTPUT_BASENAME, --output_basename OUTPUT_BASENAME
                        default basename for --write options used without
                        filename
  -p [PDBQT_FILENAME ...], --write_pdbqt [PDBQT_FILENAME ...]
                        adds _rigid/_flex with flexible residues (filename
                        defaults to --output_basename when not specified)
  -j [JSON_FILENAME ...], --write_json [JSON_FILENAME ...]
                        parameterized receptor (filename defaults to
                        --output_basename when not specified)
  --write_pdb [PDB_FILENAME ...]
                        prepared receptor (must specify filename)
  -g [GPF_FILENAME ...], --write_gpf [GPF_FILENAME ...]
                        autogrid input file (filename defaults to
                        --output_basename when not specified)
  -v [VINA_BOX_FILENAME ...], --write_vina_box [VINA_BOX_FILENAME ...]
                        config file for Vina with box dimensions (filename
                        defaults to --output_basename when not specified_
  --debug_fn DEBUG_FN   log debug level to filename

Receptor perception:
  -n SET_TEMPLATE, --set_template SET_TEMPLATE
                        e.g. A:5,7=CYX,B:17=HID
  -d DELETE_RESIDUES, --delete_residues DELETE_RESIDUES
                        e.g. A:350,B:15,16,17
  -b BLUNT_ENDS, --blunt_ends BLUNT_ENDS
                        e.g. A:123,200=2,A:1=0
  --add_templates ADD_TEMPLATES
                        Additional residue templates. Can be a JSON file path
                        or 'resname:file.sdf'.
  --cache_templates [CACHE_TEMPLATES]
                        Turns on caching of ResidueChemTemplates (default is
                        OFF) by this option and (optionally) a provided JSON
                        filename. Default cache filename is:
                        $HOME/.meeko_residue_chem_templates_cached.json) When
                        the caching is ON, the templates for polymer
                        construction will be read from the specified cache
                        file and updates may be made to the same file in a
                        cumulative manner.
  --mk_config JSON_FILENAME
                        [.json]
  -a, --allow_bad_res   delete residues with missing atoms instead of raising
                        error
  --default_altloc DEFAULT_ALTLOC
                        default alternate location (overridden by
                        --wanted_altloc)
  --wanted_altloc WANTED_ALTLOC
                        require altloc for specific residues, e.g. :5=B,B:17=A
  -f FLEXRES, --flexres FLEXRES
                        specify the flexible residues by the chain ID and
                        residue number, e.g. -f ":42,B:23" is equivalent to -f
                        ":42" -f "B:23" (leave chain ID empty if omitted in
                        input PDB or mmCIF)
  -t ROT_TERMINAL_GROUP, --rot_terminal_group ROT_TERMINAL_GROUP
                        specify the residues for which to make terminal
                        functional group rotatable by the chain ID and residue
                        number, e.g. -t ":42,B:23" is equivalent to -t ":42"
                        -t "B:23" (leave chain ID empty if omitted in input
                        PDB or mmCIF)
  --charge_model {gasteiger,espaloma,zero,read}
                        default is gasteiger, 'zero' sets all zeros, 'read'
                        requires --read_pqr

Size and center of grid box:
  --box_size X Y Z      size of grid box (x, y, z) in Angstrom
  --box_center X Y Z    center of grid box (x, y, z) in Angstrom
  --box_center_off_reactive_res
                        project grid box center along CA-CB bond 5 A away from
                        CB (only applicable when there is exactly one reactive
                        flexible residue)
  --box_enveloping FILENAME
                        Box will envelop atoms in this file [.sdf .mol .mol2
                        .pdb .pdbqt]
  --padding PADDING     padding around atoms passed to --box_enveloping [A]

Reactive:
  -r REACTIVE_FLEXRES, --reactive_flexres REACTIVE_FLEXRES
                        same as --flexres but for reactive residues (max 8)
  --reactive_name REACTIVE_NAME
                        set name of reactive atom of a residue type, e.g:
                        --reactive_name 'TRP:NE1'. Repeat flag for multiple
                        assignments. Overridden by --reactive_name_specific
  -s REACTIVE_NAME_SPECIFIC, --reactive_name_specific REACTIVE_NAME_SPECIFIC
                        set name of reactive atom for an individual residue by
                        the residue ID, e.g: -s 'A:42=NE2'. Residue will be
                        reactive.
  --r_eq_12 R_EQ_12     r_eq for reactive atoms (1-2 interaction)
  --eps_12 EPS_12       epsilon for reactive atoms (1-2 interaction)
  --r_eq_13_scaling R_EQ_13_SCALING
                        r_eq scaling for 1-3 interaction across reactive atoms
  --r_eq_14_scaling R_EQ_14_SCALING
                        r_eq scaling for 1-4 interaction across reactive atoms

@> 18957 atoms and 1 coordinate set(s) were parsed in 0.07s.

mk_prepare_receptor.py -i /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/mirror_target_prep/L-8cf1_receptor_atoms.pdb -o /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/mirror_target_prep/L-8cf1_prep -p --write_pdb /var/home/aeersriv/Documents/antibiotics_mirror_life/comp_code-antibiotics_mirror_life/notebooks/../data/mirror_target_prep/L-8cf1_prep.pdb -v --box_center -248.1948125 -311.26956249999995 -211.46221874999995 --box_size 20.0 20.0 20.0 --allow_bad_res --default_altloc
usage: mk_prepare_receptor.py [-h] [--read_pdb PDB_FILENAME]
                              [--read_pqr PQR_FILENAME] [-i MACROMOL_FILENAME]
                              [-o OUTPUT_BASENAME] [-p [PDBQT_FILENAME ...]]
                              [-j [JSON_FILENAME ...]]
                              [--write_pdb [PDB_FILENAME ...]]
                              [-g [GPF_FILENAME ...]]
                              [-v [VINA_BOX_FILENAME ...]]
                              [--debug_fn DEBUG_FN] [-n SET_TEMPLATE]
                              [-d DELETE_RESIDUES] [-b BLUNT_ENDS]
                              [--add_templates ADD_TEMPLATES]
                              [--cache_templates [CACHE_TEMPLATES]]
                              [--mk_config JSON_FILENAME] [-a]
                              [--default_altloc DEFAULT_ALTLOC]
                              [--wanted_altloc WANTED_ALTLOC] [-f FLEXRES]
                              [-t ROT_TERMINAL_GROUP]
                              [--charge_model {gasteiger,espaloma,zero,read}]
                              [--box_size X Y Z] [--box_center X Y Z]
                              [--box_center_off_reactive_res]
                              [--box_enveloping FILENAME] [--padding PADDING]
                              [-r REACTIVE_FLEXRES]
                              [--reactive_name REACTIVE_NAME]
                              [-s REACTIVE_NAME_SPECIFIC] [--r_eq_12 R_EQ_12]
                              [--eps_12 EPS_12]
                              [--r_eq_13_scaling R_EQ_13_SCALING]
                              [--r_eq_14_scaling R_EQ_14_SCALING]

options:
  -h, --help            show this help message and exit

Input/Output:
  --read_pdb PDB_FILENAME
                        reads PDB, not PDBQT, and does not use ProDy
  --read_pqr PQR_FILENAME
                        reads PQR and does not use ProDy
  -i MACROMOL_FILENAME, --read_with_prody MACROMOL_FILENAME
                        reads PDB/mmCIF file with Prody
  -o OUTPUT_BASENAME, --output_basename OUTPUT_BASENAME
                        default basename for --write options used without
                        filename
  -p [PDBQT_FILENAME ...], --write_pdbqt [PDBQT_FILENAME ...]
                        adds _rigid/_flex with flexible residues (filename
                        defaults to --output_basename when not specified)
  -j [JSON_FILENAME ...], --write_json [JSON_FILENAME ...]
                        parameterized receptor (filename defaults to
                        --output_basename when not specified)
  --write_pdb [PDB_FILENAME ...]
                        prepared receptor (must specify filename)
  -g [GPF_FILENAME ...], --write_gpf [GPF_FILENAME ...]
                        autogrid input file (filename defaults to
                        --output_basename when not specified)
  -v [VINA_BOX_FILENAME ...], --write_vina_box [VINA_BOX_FILENAME ...]
                        config file for Vina with box dimensions (filename
                        defaults to --output_basename when not specified_
  --debug_fn DEBUG_FN   log debug level to filename

Receptor perception:
  -n SET_TEMPLATE, --set_template SET_TEMPLATE
                        e.g. A:5,7=CYX,B:17=HID
  -d DELETE_RESIDUES, --delete_residues DELETE_RESIDUES
                        e.g. A:350,B:15,16,17
  -b BLUNT_ENDS, --blunt_ends BLUNT_ENDS
                        e.g. A:123,200=2,A:1=0
  --add_templates ADD_TEMPLATES
                        Additional residue templates. Can be a JSON file path
                        or 'resname:file.sdf'.
  --cache_templates [CACHE_TEMPLATES]
                        Turns on caching of ResidueChemTemplates (default is
                        OFF) by this option and (optionally) a provided JSON
                        filename. Default cache filename is:
                        $HOME/.meeko_residue_chem_templates_cached.json) When
                        the caching is ON, the templates for polymer
                        construction will be read from the specified cache
                        file and updates may be made to the same file in a
                        cumulative manner.
  --mk_config JSON_FILENAME
                        [.json]
  -a, --allow_bad_res   delete residues with missing atoms instead of raising
                        error
  --default_altloc DEFAULT_ALTLOC
                        default alternate location (overridden by
                        --wanted_altloc)
  --wanted_altloc WANTED_ALTLOC
                        require altloc for specific residues, e.g. :5=B,B:17=A
  -f FLEXRES, --flexres FLEXRES
                        specify the flexible residues by the chain ID and
                        residue number, e.g. -f ":42,B:23" is equivalent to -f
                        ":42" -f "B:23" (leave chain ID empty if omitted in
                        input PDB or mmCIF)
  -t ROT_TERMINAL_GROUP, --rot_terminal_group ROT_TERMINAL_GROUP
                        specify the residues for which to make terminal
                        functional group rotatable by the chain ID and residue
                        number, e.g. -t ":42,B:23" is equivalent to -t ":42"
                        -t "B:23" (leave chain ID empty if omitted in input
                        PDB or mmCIF)
  --charge_model {gasteiger,espaloma,zero,read}
                        default is gasteiger, 'zero' sets all zeros, 'read'
                        requires --read_pqr

Size and center of grid box:
  --box_size X Y Z      size of grid box (x, y, z) in Angstrom
  --box_center X Y Z    center of grid box (x, y, z) in Angstrom
  --box_center_off_reactive_res
                        project grid box center along CA-CB bond 5 A away from
                        CB (only applicable when there is exactly one reactive
                        flexible residue)
  --box_enveloping FILENAME
                        Box will envelop atoms in this file [.sdf .mol .mol2
                        .pdb .pdbqt]
  --padding PADDING     padding around atoms passed to --box_enveloping [A]

Reactive:
  -r REACTIVE_FLEXRES, --reactive_flexres REACTIVE_FLEXRES
                        same as --flexres but for reactive residues (max 8)
  --reactive_name REACTIVE_NAME
                        set name of reactive atom of a residue type, e.g:
                        --reactive_name 'TRP:NE1'. Repeat flag for multiple
                        assignments. Overridden by --reactive_name_specific
  -s REACTIVE_NAME_SPECIFIC, --reactive_name_specific REACTIVE_NAME_SPECIFIC
                        set name of reactive atom for an individual residue by
                        the residue ID, e.g: -s 'A:42=NE2'. Residue will be
                        reactive.
  --r_eq_12 R_EQ_12     r_eq for reactive atoms (1-2 interaction)
  --eps_12 EPS_12       epsilon for reactive atoms (1-2 interaction)
  --r_eq_13_scaling R_EQ_13_SCALING
                        r_eq scaling for 1-3 interaction across reactive atoms
  --r_eq_14_scaling R_EQ_14_SCALING
                        r_eq scaling for 1-4 interaction across reactive atoms

mk_prepare_receptor.py: error: argument --default_altloc: expected one argument
@> 94181 atoms and 1 coordinate set(s) were parsed in 0.40s.

TypeError: atoms must be an Atomic instance

## Docking

In [62]:
ligand_targets: dict[str, list[str]] = {
        "6I1H": [
            "amoxicillin", # penicillins
            "piperacillin",
            "ticarcillin",
            "cefepime", # cephalosporins
            "cefazolin",
            "ceftolozane",
            "ceftriaxone",
            "ceftazidime",
            "aztreonam", # monobactam
            "imipenem", # carbapenems
            "meropenem",
            "doripenem"
        ],
        "5M18": [
            "amoxicillin", # penicillins
            "piperacillin",
            "ticarcillin",
            "cefepime", # cephalosporins
            "cefazolin",
            "ceftolozane",
            "ceftriaxone",
            "ceftazidime",
            "aztreonam", # monobactam
            "imipenem", # carbapenems
            "meropenem",
            "doripenem"
        ],
        "8CF1": [ # 30S subunit
            "minocycline", # tetracyclines
            "tigecycline",
            "doxycycline",
            "tetracycline",
            "Chlortetracycline",
            "amikacin", # aminoglycosides
            "tobramycin",
            "streptomycin",
            "kanamycin"
        ],
        "5IQB": [ "amikacin", # aminoglycosides
            "tobramycin",
            "streptomycin",
            "kanamycin"
        ],
        "8CGD": [ # 50S subunit
            "azithromycin", # macrolides
            "erythromycin",
            "clarithromycin",
            "chloramphenicol" # chlorampenicol
        ],
        "3FL9": [
            "trimethoprim" # trimethoprim
        ],
        "1TX2": [
            "sulfamethoxazole" # sulfamethoxazole
        ],
        "4DUH": [
            "ciprofloxacin", # quinolones
            "levofloxacin",
            "Moxifloxacin"
        ]
    }

In [63]:
receptors = ["6I1H", "8CF1", "L-6I1H", "L-8CF1"]

In [66]:
receptor_info

{'6i1h': {'size': [20.0, 20.0, 20.0],
  'center': [np.float64(-5.978153846153846),
   np.float64(-52.50296153846154),
   np.float64(38.259846153846155)]},
 'L-6i1h': {'size': [20.0, 20.0, 20.0],
  'center': [np.float64(5.978153846153846),
   np.float64(52.50296153846154),
   np.float64(-38.259846153846155)]},
 '5m18': {'size': [20.0, 20.0, 20.0],
  'center': [np.float64(19.421823529411764),
   np.float64(-18.162411764705883),
   np.float64(-52.577411764705886)]},
 'L-5m18': {'size': [20.0, 20.0, 20.0],
  'center': [np.float64(-19.421823529411764),
   np.float64(18.162411764705883),
   np.float64(52.577411764705886)]},
 '8cf1': {'size': [20.0, 20.0, 20.0],
  'center': [np.float64(248.1948125),
   np.float64(311.26956249999995),
   np.float64(211.46221874999995)]},
 'L-8cf1': {'size': [20.0, 20.0, 20.0],
  'center': [np.float64(-248.1948125),
   np.float64(-311.26956249999995),
   np.float64(-211.46221874999995)]}}

In [64]:
import vina

In [70]:
out = f"{CWD}/../data/vina"
for rc in receptors:
    exhaustiveness = 8

    rcTXT = f"{CWD}/../data/native_target_prep/{rc.lower()}_prep.box.txt"
    rcPDBQT = f"{CWD}/../data/native_target_prep/6i1h_prep.pdbqt"
    if rc.startswith("L-"):
        rcTXT = f"{CWD}/../data/mirror_target_prep/L-{rc.lower()}_prep.box.txt"
        rcPDBQT = f"{CWD}/../data/mirror_target_prep/L-6i1h_prep.pdbqt"

    for lg in ligand_targets[rc]:
        nat_ligPDBQT = f"{CWD}/../data/ligand_prep/Native_{lg.title()}.pdbqt"
        mir_ligPDBQT = f"{CWD}/../data/ligand_prep/Mirror_{lg.title()}.pdbqt"
        nat_outputPDBQT = f"{out}/{lg}-{rc}_vina.pdbqt" #@param {type:"string"}
        mir_outputPDBQT = f"{out}/Mirror_{lg}-{rc}_vina.pdbqt" #@param {type:"string"}

        v1 = vina.Vina()
        v1.set_receptor(rcPDBQT)
        v1.compute_vina_maps(
            center=receptor_info[rc.lower()]["center"],
            box_size=receptor_info[rc.lower()]["size"])
        v1.set_ligand_from_file(nat_ligPDBQT)
        v1.dock(exhaustiveness=exhaustiveness)
        v1.write_poses(nat_outputPDBQT)

        v2 = vina.Vina()
        v2.set_receptor(rcPDBQT)
        v2.compute_vina_maps(
            center=receptor_info[f"L-{rc.lower()}"]["center"],
            box_size=receptor_info[f"L-{rc.lower()}"]["size"]
        )
        v2.set_ligand_from_file(mir_ligPDBQT)
        v2.dock(exhaustiveness=exhaustiveness)
        v2.write_poses(mir_outputPDBQT)

Computing Vina grid ... done.
Performing docking (random seed: -1881765891) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -7.889          0          0
   2       -7.888      3.418      4.722
   3       -7.723      3.271      8.704
   4       -7.707      1.797      2.334
   5       -7.305      5.381      6.826
   6       -7.297      3.607      5.382
   7       -7.257      2.766      4.563
   8       -7.219      5.306      10.89
   9       -7.189       5.56       10.4
  10       -6.943      3.815      5.781
  11       -6.789      5.065      10.73
  12       -6.614      5.168      11.28
  13       -6.558      6.973      9.672
  14       -6.556       3.29      4.971
  15       -6.522      5.169      9.628
  16       -6.447      4.521      9.565
  17       -6.391      4.602      8.082
  18       -6.273      4.813      6.074
  19       -6.237      3.699      4.986
  20       -6.221      6.573      11.12
Computing Vina grid ... done.

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Performing docking (random seed: 405334830) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2    0.0006341      4.515      6.924
   3    0.0006398       9.13      10.89
   4    0.0006576      7.971      10.97
   5    0.0007108      4.284      6.269
   6    0.0007238      9.897      12.58
   7    0.0007288      13.07       15.1
   8    0.0008253      4.848      7.992
   9    0.0008259      5.535      7.289
  10    0.0008259      8.876      11.82
  11    0.0008358      4.245      6.765
  12    0.0008406      5.352      8.388
  13    0.0008406      6.167      9.168
  14    0.0008957      5.821       8.33
  15    0.0009365      3.484      6.906
  16     0.001109      5.854      7.787
  17     0.001114      5.556      9.047
  18     0.001416      6.218      8.363
  19     0.001446       4.75      7.855
  20     0.001859      10.34      11.89
Computing Vina grid ... done.
Performing docking (random seed: -1075611630) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -8.552          0          0
   2        -8.28      3.332      4.957
   3       -8.057      2.788      4.436
   4       -7.974      3.506      5.395
   5       -7.704      3.302       8.78
   6       -7.703      3.834       9.64
   7       -7.235      3.098      9.259
   8       -7.229      1.752      2.072
   9        -7.06      3.625      5.671
  10       -6.883      3.671      8.287
  11       -6.627      4.106      6.571
  12       -6.549      2.568      3.017
  13       -6.434      3.488      4.662
  14        -6.39      2.164      2.811
  15       -6.357      3.618       5.23
  16       -6.351      4.142      5.949
  17       -6.293      4.69

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.
WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

8      8.181
  18       -6.287      2.591      3.139
  19       -6.254      4.315       9.27
  20        -6.11      3.155      9.794
Computing Vina grid ... done.
Performing docking (random seed: 2007989085) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2    0.0001085      4.149      6.334
   3    0.0001503      8.095      9.222
   4    0.0001523      3.283       5.86
   5    0.0001765      5.115      5.888
   6    0.0002796      5.607      8.345
   7    0.0007493       4.27      8.253
   8    0.0009403      4.218      8.162
   9    0.0009436      5.648      9.317
  10    0.0009674       3.43      6.115
  11     0.001093      4.883      8.481
  12      0.00119      4.194      9.234
  13     0.001304      4.617      8.248
  14     0.001342      7.414      9.697
  15      0.00203      4.794      8.029
  16     0.002554      5.315      7.725
  17     0.002789       7.86      10.68
  18     0.003468      5.738      9.949
  19     0.004154      6.703      10.11
  20     0.004482       5.94       8.99
Computing Vina grid ... done.

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.
WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Performing docking (random seed: -1374146825) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -7.874          0          0
   2       -7.601      1.424      1.706
   3       -7.597      1.837      2.582
   4       -7.343      2.975      3.902
   5        -7.24      2.851      4.193
   6       -7.064      3.824      6.325
   7       -7.057      2.379      3.012
   8       -7.043      1.826      2.504
   9       -6.938      3.007      3.819
  10       -6.916      2.157      7.353
  11        -6.76      2.523      7.336
  12       -6.729      3.184      4.497
  13       -6.707      2.884      3.823
  14       -6.649      2.492      6.892
  15       -6.618      3.479      7.648
  16       -6.603      3.722      7.079
  17       -6.594      4.626      6.517
  18       -6.243      2.158       2.69
  19       -6.241      3.935      5.789
  20       -6.236       4.25      5.953
Computing Vina grid ... done.
Performing docking (random seed: 1527938758) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2    5.675e-06      11.11      12.95
   3    8.216e-05      7.007      10.49
   4    0.0001808      9.253      11.06
   5    0.0002122      5.141      7.746
   6    0.0002124      4.924      8.085
   7    0.0002125      7.383      9.243
   8    0.0002401      5.185      8.263
   9     0.000244      7.692      10.96
  10    0.0002577      4.904      9.632
  11    0.0002617      5.107      7.082
  12    0.0004452      11.54      14.21
  13    0.0009492      3.557      6.291
  14    0.0009493      4.568      8.326
  15    0.0009549      10.16      13.05
  16    0.0009649       3.79      6.354
  17      0.00101

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

 5.655      7.224
  18     0.001012      8.186      9.845
  19     0.001234      8.591      11.32
  20     0.001532      4.222      7.076
Computing Vina grid ... done.
Performing docking (random seed: -281325394) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -8.863          0          0
   2       -8.286       1.86      2.878
   3       -8.217      3.121       8.95
   4       -7.891      3.428      9.308
   5       -7.525      2.868      4.268
   6       -7.504      2.337      3.648
   7       -7.208      2.347      3.162
   8       -7.183      1.851      2.512
   9        -7.14      2.384      2.745
  10       -6.953      3.692      5.378
  11       -6.902      3.514      8.404
  12       -6.612        3.2       4.72
  13       -6.556      2.662       3.95
  14       -6.551      2.817      4.003
  15       -6.459      4.148      7.174
  16       -6.416      2.165      3.307
  17        -6.35      3.364      9.287
  18       -6.336      2.888      8.397
  19       -6.169      2.871      4.022
  20        -5.96      2.709      4.154
Computing Vina grid ... done.
Performing docking (random seed: 1791352084) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2    5.491e-05      10.07      12.12
   3    8.487e-05      5.074      9.371
   4    0.0009482      4.982      7.353
   5     0.001052      6.259      9.387
   6     0.001179      4.583      9.645
   7     0.001216      4.702      6.691
   8     0.001357      3.251      8.457
   9      0.00141      3.564      8.539
  10     0.001428      3.461      4.839
  11     0.001455      4.212      5.486
  12     0.001507      6.734      9.311
  13     0.001543      3.444      8.955
  14     0.001621      8.466      11.03
  15     0.001668      3.955      6.485
  16       0.0017      8.105      10.02
  17      0.00172      6.474      9.553
  18     0.001792      6.349      10.43
  19     0.001997      8.611      10.99
  20     0.002446      11.44       15.2

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.
WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Computing Vina grid ... done.

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Performing docking (random seed: 840201267) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -9.125          0          0
   2       -9.096      1.042      1.098
   3        -8.82      1.884      2.336
   4        -8.37      2.819      9.291
   5       -8.147      2.058      9.881
   6        -7.98      3.021      8.895
   7       -7.911      4.642      10.34
   8       -7.453      4.634      6.268
   9       -7.414      4.975      6.835
  10        -7.38      5.108        9.5
  11       -7.365      3.062      8.793
  12       -7.276      5.747       9.42
  13       -7.254      2.063      9.254
  14       -6.866      3.502      9.026
  15       -6.851      4.353      5.439
  16       -6.808      2.977      9.873
  17       -6.772      4.287      9.464
  18       -6.695      3.965      5.482
  19       -6.621      3.245      9.745
  20       -6.513      5.008      6.143

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Computing Vina grid ... done.
Performing docking (random seed: -1357522685) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2    0.0001225      8.639      10.81
   3    0.0004467      6.983      8.743
   4    0.0005745      2.568       2.91
   5    0.0007297      6.964      10.82
   6    0.0007689      10.06      12.73
   7     0.001079      5.931      7.932
   8     0.001116      5.773       8.93
   9     0.001269      9.074      11.61
  10     0.001293      8.958      10.92
  11     0.001321      8.399      9.867
  12     0.001452      3.669      5.941
  13       0.0019      9.464      11.62
  14     0.001983      5.904      8.558
  15     0.002107      5.019      8.539
  16     0.002165      7.095      9.439
  17     0.002231      3.685      5.438
  18      0.00227      6.435      10.53
  19     0.002583      4.418      7.379
  20     0.003104      6.583      10.26
Computing Vina grid ... done.
Performing docking (random seed: 889529563) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -8.234          0          0
   2       -7.902      2.718      5.476
   3       -7.394      1.654      2.171
   4       -7.347      2.646      4.837
   5       -7.324      2.089      3.832
   6       -7.224      2.614       3.87
   7       -7.102      3.314      7.329
   8       -7.027      1.794      2.213
   9        -6.98      2.315      3.445
  10       -6.953       2.99      7.179
  11       -6.937      3.246      11.88
  12       -6.887      2.714      4.355
  13       -6.848      2.491      4.283
  14       -6.822      3.892      6.171
  15       -6.784      3.035      4.653
  16       -6.683      3.163       5.08
  17       -6.618      3.812      5.771
  18       -6.579      3.017      11.96
  19       -6.505      3.688      7.812
  20       -6.267      2.551      4.513
Computing Vina grid ... done.

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.
WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Performing docking (random seed: 1663817362) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2     0.002221      5.254       8.73
   3     0.002757      5.432      6.897
   4     0.002921      6.551      10.95
   5     0.003366      3.646      7.122
   6     0.003463      7.412      12.23
   7     0.005155      4.508      7.889
   8     0.005868       4.24      7.168
   9     0.007551      4.483      9.483
  10     0.007734      5.967       10.1
  11     0.009518      7.216       9.89
  12      0.01087      6.438      7.587
  13      0.01106      3.677      7.796
  14      0.01113      3.588      6.429
  15      0.01181      8.091      12.28
  16      0.01182      4.687      8.153
  17      0.01208      6.325      8.695
  18      0.01464      6.257      9.337
  19      0.02014      6.901       11.3
  20      0.03527      6.733      10.12
Computing Vina grid ... done.
Performing docking (random seed: 452778600) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -9.368          0          0
   2       -8.961      1.622      1.839
   3       -8.922      2.427      10.11
   4       -8.828      1.014       1.72
   5       -8.718      1.424      2.724
   6       -8.638      1.441      2.063
   7       -8.612      2.429      10.55
   8        -8.07      3.365      6.443
   9       -8.043      2.148       3.32
  10       -7.946      3.584      4.899
  11       -7.922      3.222      3.881
  12       -7.515      2.382      3.026
  13       -7.506        2.6      10.87
  14       -7.476      3.988      10.18
  15       -7.445      2.607      10.35
  16       -7.226      3.088        9.3
  17       -7.188       3.86      6.651
  18       -7.176      2.642      10.19
  19       -7.125      3.713      9.527
  20       -7.031       3.42      10.02
Computing Vina grid ... done.

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.
WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Performing docking (random seed: 2021463220) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2     0.002494      4.507      7.161
   3     0.002775      4.555      8.615
   4     0.002934      3.943      5.955
   5     0.003544      5.334      6.821
   6     0.003579      7.157      10.05
   7     0.004072      2.533      5.672
   8     0.004072      4.052      6.657
   9     0.004492      4.032      7.196
  10     0.004551      5.466      7.049
  11     0.004938      4.597      7.254
  12     0.005028      2.637      3.267
  13     0.005033      5.886      7.965
  14     0.005138      3.821      6.115
  15     0.005243      6.844      9.554
  16     0.005506      3.686      8.146
  17      0.00577      7.087      10.17
  18     0.006275      3.247      4.686
  19     0.007535      3.641      8.019
  20     0.008399      5.631      8.864
Computing Vina grid ... done.
Performing docking (random seed: -650238173) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -8.427          0          0
   2       -8.349      2.533      4.143
   3       -8.066      1.994      4.207
   4       -7.869      2.611      8.885
   5       -7.773      2.975      9.101
   6       -7.732      1.376       2.21
   7       -7.065      2.131      4.011
   8        -7.05      2.768      8.566
   9       -6.959      3.676       8.56
  10       -6.927      3.161       9.01
  11       -6.828       3.63      8.781
  12       -6.691      2.758      8.919
  13       -6.431      3.434      9.068
  14        -6.26       3.28       9.07
  15        -6.12       2.95      8.981
  16       -6.115      2.611      4.578
  17       -5.923      3.094      4.391
  18       -5.823      4.578      9.242
  19       -5.752      3.725      8.537
  20       -5.718      3.797      8.986
Computing Vina grid ...

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

done.
Performing docking (random seed: -104085710) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2     0.000487      6.713      10.86
   3    0.0005784       5.56      7.266
   4    0.0007613      5.662      8.824
   5      0.00104      7.049       10.9
   6     0.001138      4.746      6.985
   7      0.00137      4.459      7.469
   8     0.001394      4.596      7.848
   9     0.001411       7.95      12.31
  10      0.00142      5.562      9.263
  11     0.001534       5.52      8.526
  12     0.001563      7.451      11.02
  13     0.001723      4.281      7.064
  14      0.00174      6.024      10.21
  15     0.001794      8.081      11.38
  16     0.001816       5.08        9.4
  17      0.00184      3.131      4.958
  18     0.001994      3.795       7.66
  19     0.002052       4.84      9.222
  20     0.002133      4.444      9.258
Computing Vina grid ... done.
Performing docking (random seed: 1935273999) ...

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.
WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -8.218          0          0
   2       -8.006      3.496      7.626
   3       -7.819      4.039        8.1
   4        -7.76       2.73      4.993
   5        -7.69      2.538      4.656
   6       -7.429      4.234      7.008
   7       -7.374       2.12      2.615
   8       -7.172      3.936      6.292
   9       -7.157       3.55       7.53
  10       -7.075      3.746      8.023
  11       -6.868      3.903      8.431
  12       -6.708      3.674      5.503
  13       -6.672       3.12      6.711
  14       -6.574      3.516      6.983
  15       -6.559      2.359      3.066
  16       -6.527      5.403       8.78
  17       -6.456      4.866      9.047
  18       -6.316      6.447      9.182
  19       -6.297      4.801      7.813
  20       -6.259       4.61      5.728
Computing Vina grid ... done.

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.
WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Performing docking (random seed: -154584206) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2     0.001232      7.523      10.14
   3      0.00135      4.901      7.615
   4     0.003732      7.344      9.581
   5     0.004492      4.239       5.83
   6     0.004698      3.638       6.95
   7     0.005284       6.03      8.428
   8     0.005986      4.448      8.313
   9     0.006042      7.442      10.45
  10     0.006376      4.656      6.117
  11     0.006704       5.14      7.262
  12     0.007051      8.991      10.46
  13     0.007077      9.888      11.95
  14     0.007184      5.958      8.553
  15     0.007201      6.445      8.488
  16     0.007222      5.919      8.091
  17     0.007266      2.857       4.18
  18     0.007321      6.194      9.223
  19     0.007333      6.502      8.322
  20     0.007407      5.539      6.596
Computing Vina grid ... done.
Performing docking (random seed: 1616806079) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -6.468          0          0
   2       -6.318      2.368      5.549
   3       -6.215      2.267      3.227
   4       -6.189      2.831      3.885
   5       -6.015      1.873      2.858
   6       -5.973      2.147      3.328
   7       -5.937      3.235      5.291
   8       -5.903      2.712      5.449
   9       -5.588      2.435      3.445
  10       -5.368      2.507      3.342
  11        -5.32      1.651      2.319
  12       -5.284      2.591      5.386
  13       -5.247      2.622      5.766
  14       -5.245      3.138      5.522
  15       -5.215      2.724      5.752
  16       -5.209      2.695      3.705
  17       -5.166      2.561      5.387
  18       -5.131      2.807      6.113
  19        -4.99      2.785      6.129
  20       -4.795      2.382      5.293
Computing Vina grid ... done.

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Performing docking (random seed: 833478044) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2    2.644e-06       12.1      13.37
   3    0.0004973      5.138      7.143
   4    0.0005859      4.223      5.997
   5    0.0006201      11.09      12.99
   6    0.0007226      9.417      10.74
   7     0.001011      2.932      4.472
   8     0.001206      5.105      6.624
   9     0.001206      5.592      7.549
  10     0.001235      9.095      11.12
  11     0.001312      9.284      11.43
  12     0.001422      7.893      9.592
  13     0.001546       11.5      13.21
  14     0.001698      6.839      9.312
  15     0.001779      5.548      8.119
  16     0.001807      10.16      12.13
  17     0.001813      5.775      7.881
  18     0.001874      5.192      7.366
  19     0.001908      12.25      14.64
  20     0.001925      7.147      9.181
Computing Vina grid ... done.

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.
WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Performing docking (random seed: -1815956062) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -8.095          0          0
   2       -7.952      1.608      1.686
   3       -7.399      3.792      8.103
   4       -7.385      2.261      3.064
   5       -7.339      1.715       1.87
   6       -7.264      2.909      4.381
   7       -7.185      2.913      8.021
   8       -7.155      3.181      4.011
   9       -7.136      1.526      2.004
  10       -7.092      2.704      3.613
  11       -7.086      3.456      4.564
  12       -6.972      2.897      3.878
  13       -6.959      2.925      3.739
  14       -6.664      2.337      2.815
  15       -6.541      2.043      2.729
  16       -6.485      2.688      3.449
  17       -6.412      3.157      5.556
  18       -6.152      2.494      7.969
  19       -6.101      2.307      7.158
  20       -5.989      3.178      4.635
Computing Vina grid ... done.
Performing docking (random seed: 2038644645) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2    0.0003015       5.66       9.11
   3    0.0003015      4.937      8.287
   4    0.0007269      12.05      14.32
   5    0.0008546      5.231      6.517
   6     0.001534      4.691      7.277
   7     0.001587      4.445      7.217
   8     0.001691       3.75      5.075
   9     0.002025      5.397      7.784
  10     0.002082      5.504      6.727
  11     0.002091      10.76      13.15
  12     0.002094      4.873      6.423
  13     0.002095      8.791      11.08
  14     0.002103      4.925      7.119
  15     0.002117      7.873      9.121
  16     0.002197      5.364      7.009
  17     0.002241      8.317      9.826
  18     0.002421      2.779      7.006
  19     0.002726      3.575      5.289
  20     0.002742      8.304      10.31
Computing Vina grid ... done.
Performing docking (random seed: -847654811) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -8.077          0          0
   2       -7.891      2.322      5.841
   3       -7.876       2.54      3.991
   4       -7.616      1.832      2.468
   5       -7.334      3.749        7.4
   6        -6.99       3.97      7.951
   7       -6.885      2.539      2.963
   8       -6.847      2.913      6.366
   9        -6.81       3.92      5.139
  10       -6.798      4.549      6.197
  11       -6.742       4.02      8.446
  12       -6.681      3.761       5.01
  13       -6.535      5.496      7.007
  14       -6.514      5.045      6.135
  15       -6.458      3.258      4.484
  16       -6.454      3.888      8.107
  17       -6.295      4.258      7.892
  18       -6.266      2.645      3.302
  19       -6.244      2.972      7.635
  20       -6.219      2.872      4.108
Computing Vina grid ... done.

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.
WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Performing docking (random seed: 2068630843) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2    0.0001443      8.815       10.5
   3    0.0003363      4.147      7.455
   4    0.0006043      6.665      8.696
   5    0.0006358      7.429      9.231
   6    0.0006358       7.02      8.833
   7    0.0007109      5.825      7.417
   8    0.0007403      5.454      8.412
   9    0.0007642      5.006      6.956
  10    0.0008363      3.912      5.846
  11    0.0008363      4.441      6.607
  12    0.0008771        7.9      9.842
  13    0.0009201      3.709       6.98
  14      0.00093      3.327       4.82
  15      0.00093      2.864      4.182
  16    0.0009536       5.64      7.927
  17     0.001004      6.739      8.736
  18     0.001099      7.646      9.471
  19     0.001137      9.124      10.96
  20     0.001212      3.335      5.457
Computing Vina grid ... done.
Performing docking (random seed: -1152088659) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2     7.02e-05      5.804      8.801
   3    7.441e-05      5.369      7.605
   4    7.441e-05      4.458       7.38
   5    7.441e-05      4.371      6.955
   6    7.441e-05      8.204      11.36
   7    7.441e-05      10.98      13.34
   8    7.441e-05      9.169      12.45
   9    7.441e-05      3.182      6.133
  10    7.441e-05      3.266      6.026
  11    7.441e-05      7.748       10.9
  12    7.441e-05      5.199      7.525
  13    7.441e-05      7.093      9.625
  14    7.715e-05      4.083       7.17
  15    7.715e-05      9.555      12.91
  16    7.715e-05       6.62      8.381
  17    8.503e-05      10.57      14.36
  18    8.568e-05      5.061      6.078
  19    0.0001082      8.557      10.74
  20    0.0001204      3.865      5.376
Computing Vina grid ... done.

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Performing docking (random seed: -178802624) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2    0.0001191       6.16      10.61
   3     0.000127      4.797      6.591
   4    0.0003053      7.152      10.66
   5    0.0003057      8.016      9.559
   6    0.0005599      7.612      12.37
   7    0.0005672      7.325       12.5
   8    0.0008752      11.44      13.05
   9    0.0008773      6.603      9.414
  10    0.0008774      4.145      6.584
  11    0.0008788      10.18      14.59
  12    0.0008789      10.06      13.07
  13    0.0008791      6.558      9.987
  14    0.0008795      6.177      8.272
  15    0.0008798      7.932       11.9
  16    0.0009135      11.42         15
  17    0.0009135      8.867      13.04
  18     0.001019      5.652      6.795
  19     0.001214      7.058      10.01
  20     0.001807      11.07      15.14

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Computing Vina grid ... done.
Performing docking (random seed: 447962579) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2    1.252e-05      6.654      10.86
   3    1.305e-05      4.754       8.17
   4    2.973e-05      5.963       7.63
   5    3.241e-05      2.831      5.933
   6    3.498e-05        7.4      11.43
   7     6.59e-05      3.219      5.018
   8    6.756e-05      5.405      8.119
   9    6.763e-05      5.919      9.633
  10    6.847e-05      2.652      3.247
  11    7.075e-05      7.099      10.08
  12    0.0001289      5.518      8.992
  13    0.0001503      4.003      5.918
  14    0.0001539      4.505      8.719
  15    0.0001662      6.765      10.62
  16    0.0001823      7.078      11.84
  17    0.0001946      5.013      9.837
  18    0.0002041      6.925      12.35
  19    0.0002233      4.769      10.59
  20    0.0002828      4.563      8.881

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Computing Vina grid ... done.
Performing docking (random seed: 1868933304) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2    0.0005863      6.167       8.67
   3    0.0006221      8.583      10.92
   4    0.0006469       5.35      11.01
   5    0.0006699      6.143      7.731
   6    0.0007382      4.688      6.705
   7    0.0008059      5.189      10.82
   8    0.0008141      3.516      4.781
   9    0.0008294      5.014        6.3
  10    0.0008473      4.059      5.521
  11    0.0008906      6.537      12.02
  12    0.0008964      4.545      6.341
  13     0.000942      5.708      11.88
  14    0.0009515      5.691      10.13
  15    0.0009573      5.242      9.823
  16    0.0009602      5.546      10.84
  17    0.0009615      6.071      8.951
  18    0.0009956      6.715       10.4
  19     0.001036      4.639      7.859
  20     0.001071      5.292      11.68

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Computing Vina grid ... done.

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Performing docking (random seed: -1561933553) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2    2.055e-06      8.414      11.57
   3    2.055e-06      4.575      5.958
   4    2.055e-06       6.86      9.207
   5    2.055e-06      7.115      8.705
   6    2.055e-06      4.267      7.049
   7    2.055e-06      5.018      8.632
   8    2.055e-06      4.441      7.537
   9     0.001006      6.737      9.542
  10     0.001009       6.82      9.537
  11      0.00101       5.35      7.394
  12      0.00101      4.801      7.047
  13      0.00101      7.488      9.796
  14     0.001011      3.053      5.176
  15     0.001012      5.428      7.755
  16     0.001012      5.985       9.06
  17     0.001012      5.896      8.912
  18     0.001012      4.191      6.483
  19     0.001014      7.045      10.17
  20     0.001017      5.504      10.08
Computing Vina grid ... done.
Performing docking (random seed: -1674937397) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2    4.524e-06       5.39      9.126
   3    4.524e-06      5.165      8.806
   4    4.524e-06      5.124      8.962
   5    7.492e-06      3.726      6.295
   6    0.0002012      4.642      7.698
   7    0.0002012      7.519      10.09
   8    0.0002012      10.54      12.89
   9    0.0002012      4.687      6.211
  10    0.0002012      8.448      10.07
  11    0.0002012      4.782       6.24
  12    0.0002063      8.111      10.62
  13    0.0002063      4.166       6.04
  14    0.0003737      5.387      9.387
  15    0.0003918      8.867      10.16
  16    0.0003924      9.631      11.38
  17    0.0003969      7.057      10.32
  18    0.0003969      4.553      7.059
  19    0.0003974      3.738      6.418
  20    0.0003974      6.223       8.83

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Computing Vina grid ... done.
Performing docking (random seed: 2006839494) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2    1.591e-06      3.507      5.131
   3    1.591e-06      4.065      8.093
   4    1.591e-06      8.084      11.54
   5    0.0008826      4.927      7.496
   6    0.0008826      5.053      6.203
   7    0.0008826      6.067      8.309
   8    0.0008826      6.615      9.384
   9    0.0008826       5.98      8.957
  10    0.0008826      4.308      7.661
  11    0.0008826      3.141      7.216
  12    0.0008826      3.267       6.78
  13    0.0008826      4.222      8.215
  14    0.0008826      1.827      2.743
  15    0.0008842       5.93      7.709
  16    0.0008842      6.047      7.817
  17    0.0008842

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

 4.183      6.251
  18    0.0008842      4.057      4.953
  19    0.0008842      3.724      5.093
  20    0.0008842      3.948      6.919
Computing Vina grid ... done.
Performing docking (random seed: 1802337113) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2            0      10.86      13.76
   3            0      9.495      11.81
   4            0      4.385      6.189
   5            0      5.346      8.936
   6            0      8.193      11.15
   7            0       8.12      10.78
   8            0      2.694        3.4
   9            0      4.558      7.357
  10            0      10.39      13.36
  11            0      4.957       6.94
  12            0      1.949      2.097
  13            0      2.718      3.186
  14            0      4.239      6.656
  15            0      4.651      6.746
  16            0      5.066      7.948
  17            0       4.28      8.069
  18            0      6.341      9.138
  19            0      9.111      11.88
  20            0      7.949      11.03
Computing Vina grid ... done.

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Performing docking (random seed: -934685830) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2            0      5.306      7.672
   3            0      4.459      6.794
   4            0      10.94      13.78
   5            0      8.499      12.72
   6            0      7.739      11.57
   7            0      9.806      12.49
   8            0      9.433       13.1
   9    5.232e-06      6.071      10.38
  10    5.232e-06      6.377      9.576
  11    5.236e-06      7.255      10.29
  12    5.236e-06      10.09      13.81
  13    5.236e-06      4.197      5.492
  14    5.236e-06       6.48      8.797
  15    5.236e-06      5.593       8.57
  16    5.236e-06      3.833      6.352
  17    5.236e-06      5.774      7.576
  18    5.236e-06      8.251      11.78
  19    5.236e-06      9.419      11.28
  20    5.236e-06      10.96      14.25
Computing Vina grid ... done.

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Performing docking (random seed: -1549474631) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2            0      8.669      11.73
   3            0      7.313       9.57
   4            0      5.151      6.834
   5            0      4.479      6.966
   6            0      8.175      10.06
   7            0      5.167      8.508
   8            0      8.932      11.42
   9            0      6.828      9.735
  10            0      5.208      7.463
  11    3.973e-06      6.127      7.399
  12    3.973e-06      12.18      14.59
  13    3.973e-06      4.855      7.089
  14    3.973e-06      11.02      12.87
  15    3.973e-06      6.679      8.857
  16    3.973e-06      7.089      8.976
  17    3.973e-06      10.19      12.34
  18    3.973e-06       11.1      13.13
  19    3.973e-06       9.02      12.38
  20    3.973e-06        9.6      12.61
Computing Vina grid ... done.

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Performing docking (random seed: 1659913752) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2     0.001165       6.49      8.499
   3     0.001538      6.104       11.1
   4     0.001995      5.105      8.507
   5     0.002432      5.312      8.278
   6     0.002913      5.392      7.277
   7     0.004316      8.201      10.38
   8     0.004372      6.897      9.005
   9      0.01106      3.741      6.844
  10      0.01773      4.998       6.26
  11      0.02548      6.076      8.469
  12      0.02553      6.503      10.98
  13      0.02563      3.973      6.582
  14      0.02563      5.177       9.35
  15      0.02683      3.644      5.419
  16      0.02716      4.008      6.016
  17      0.02719      4.633      8.194
  18      0.02952      4.857      8.027
  19      0.03106      4.467      6.506
  20       0.0328      5.612      8.866
Computing Vina grid ... done.

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.
WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Performing docking (random seed: -1503024302) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2    6.362e-05      8.346       10.6
   3    9.648e-05        5.5      8.222
   4    0.0001072      9.494      14.13
   5    0.0001887      4.949      7.155
   6    0.0002091      3.033      8.156
   7    0.0002907      7.568      11.76
   8    0.0002922      6.393      7.984
   9    0.0002951       9.84      12.61
  10    0.0002987      6.271      9.518
  11    0.0003041      9.502      13.91
  12    0.0003107      5.016      7.031
  13    0.0003133      4.501      6.492
  14    0.0003271      6.618      9.202
  15    0.0004074      6.069      10.96
  16     0.000423      4.393      5.442
  17    0.0006033      3.594      6.615
  18    0.0006118       8.28      11.85
  19    0.0006398      6.654      10.06
  20    0.0007291      7.166      11.61
Computing Vina grid ...

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

done.
Performing docking (random seed: 676982508) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2     0.001074      9.148      9.976
   3     0.001166      9.672      12.82
   4     0.001584      4.586      7.368
   5     0.001618       5.07       7.47
   6     0.001641      2.954      7.243
   7     0.001649      10.95      13.97
   8     0.001787      5.445      7.965
   9      0.00192      3.328      6.105
  10     0.002113      3.776      8.491
  11      0.00229      5.128      8.048
  12     0.002622      6.846      10.55
  13     0.003124      6.279      8.593
  14     0.003146      8.697      10.69
  15     0.003198      3.478      7.441
  16     0.003213      3.803      5.638
  17      0.00323      6.137      8.954
  18     0.003237      10.11      13.22
  19     0.003351      6.447       9.88
  20     0.003351      7.937      12.66
Computing Vina grid ... done.

WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.

Performing docking (random seed: 1135126107) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1            0          0          0
   2            0      5.564      8.004
   3      0.00044        8.2      12.02
   4    0.0004413      10.43       12.1
   5    0.0004421      7.796      11.69
   6    0.0004511      6.254      10.02
   7    0.0004511      4.889      8.819
   8    0.0004525      5.569      9.126
   9    0.0005835      6.677      9.572
  10     0.001245      4.011      9.195
  11     0.001246       8.11      10.93
  12      0.00152      5.792      8.436
  13     0.001522      7.057      11.16
  14     0.001522      10.03      12.15
  15     0.001527      2.862      6.847
  16     0.001529      6.314       9.54
  17     0.001532      4.954      6.758
  18     0.001534      13.44      16.07
  19     0.001537      8.889      11.97
  20     0.001543      5.988      7.574
Computing Vina grid ...

:

: