---
This is metadata:

Kernel: bioinformatics (Python 3.14.0)
Path:   /var/home/aeersriv/.anaconda3/envs/bioinformatics/bin/python
---

# Ligands Retrieval (Stage 0.1.0)

Retrieve all ligands from NCBI PubChem via PUGREST API

> This has been run and ligands were retrieved. **DO NOT RUN**
> to avoid unnecessary server compute time use. Proceed to Analysis.

## Preliminaries

In [1]:
import pandas as pd
from pubchempy import Compound, get_compounds, download

## Dataset

In [6]:
antibiotics = pd.read_csv("../data/ANTIBIOTICS-FLD1.csv")
antibiotics

           antibiotic abbreviation        cid antibiotic_class who_class
0         Amoxicillin          AMX      33613      beta_lactam       CIA
1        Piperacillin          PIP      43672      beta_lactam       CIA
2         Ticarcillin          TIC      36921      beta_lactam       CIA
3            Cefepime          FEP    5479537      beta_lactam       CIA
4           Cefazolin          CZO      33255      beta_lactam       HIA
5         Ceftolozane          CZT   53234134      beta_lactam       CIA
6         Ceftriaxone          CRO    5479530      beta_lactam       CIA
7         Ceftazidime          CAZ    5481173      beta_lactam       CIA
8           Aztreonam          ATM    5742832      beta_lactam       CIA
9            Imipenem          IPM     104838      beta_lactam       CIA
10          Meropenem          MEM     441130      beta_lactam       CIA
11          Doripenem          DOR      73303      beta_lactam       CIA
12         Vancomycin          VAN      14969     glycopeptide       CIA
13        Tigecycline          TGC   54686904    glycylcycline       CIA
14        Minocycline          MNO   54675783     tetracycline       HIA
15        Doxycycline          DOX   54671203     tetracycline       HIA
16       Tetracycline          TCY   54675776     tetracycline       HIA
17  Chlortetracycline          CTE   54675777     tetracycline       HIA
18       Azithromycin          AZM     447043        macrolide       CIA
19       Erythromycin          ERY      12560        macrolide       CIA
20     Clarithromycin          CLR      84029        macrolide       CIA
21    Chloramphenicol          CHL       5959       amphenicol       HIA
22          Linezolid          LNZ     441401    oxazolidinone       CIA
23         Rifampicin          RIF  135398735        ansamycin       CIA
24         Fosfomycin          FOS     446987       phosphonic       CIA
25           Amikacin          AMK      37768   aminoglycoside       CIA
26         Tobramycin          TOB      36294   aminoglycoside       CIA
27       Streptomycin          STR      19649   aminoglycoside       CIA
28          Kanamycin          KAN       6032   aminoglycoside       CIA
29       Trimethoprim          TMP       5578     trimethoprim       HIA
30   Sulfamethoxazole          SMX       5329      sulfonamide       HIA
31      Ciprofloxacin          CIP       2764        quinolone       CIA
32       Levofloxacin          LVX     149096        quinolone       CIA
33       Moxifloxacin          MFX     152946        quinolone       CIA

In [5]:
ab_cid: dict[str, dict] = {}

for ab in antibiotics["antibiotic"]:
    res = get_compounds(ab, "name", record_type="3d")
    if len(res) == 0:
        res = get_compounds(ab, "name")
    cid = res[0].cid
    ab_cid[ab] = Compound.from_cid(cid).to_dict(
            [
                "cid",
                "smiles",
                "inchi",
            ]
        )
    download(
        "sdf", f"../data/ligands/sdf/{cid}.sdf", cid, overwrite=True
    )

In [7]:
compound_query = pd.DataFrame(ab_cid)
compound_query

,Amoxicillin,Piperacillin,Ticarcillin,Cefepime,Cefazolin,Ceftolozane,Ceftriaxone,Ceftazidime,Aztreonam,Imipenem,...,Fosfomycin,Amikacin,Tobramycin,Streptomycin,Kanamycin,Trimethoprim,Sulfamethoxazole,Ciprofloxacin,Levofloxacin,Moxifloxacin
cid,33613,43672,36921,5479537,33255,53234134,5479530,5481173,5742832,104838,...,446987,37768,36294,19649,6032,5578,5329,2764,149096,152946
smiles,CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H]...,CCN1CCN(C(=O)C1=O)C(=O)N[C@H](C2=CC=CC=C2)C(=O...,CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H]...,C[N+]1(CCCC1)CC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)...,CC1=NN=C(S1)SCC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)...,CC(C)(C(=O)O)O/N=C(/C1=NSC(=N1)N)\C(=O)N[C@H]2...,CN1C(=NC(=O)C(=O)N1)SCC2=C(N3[C@@H]([C@@H](C3=...,CC(C)(C(=O)O)O/N=C(/C1=CSC(=N1)N)\C(=O)N[C@H]2...,C[C@H]1[C@@H](C(=O)N1S(=O)(=O)O)NC(=O)/C(=N\OC...,C[C@H]([C@@H]1[C@H]2CC(=C(N2C1=O)C(=O)O)SCCN=CN)O,...,C[C@H]1[C@H](O1)P(=O)(O)O,C1[C@@H]([C@H]([C@@H]([C@H]([C@@H]1NC(=O)[C@H]...,C1[C@@H]([C@H]([C@@H]([C@H]([C@@H]1N)O[C@@H]2[...,C[C@H]1[C@@]([C@H]([C@@H](O1)O[C@@H]2[C@H]([C@...,C1[C@H]([C@@H]([C@H]([C@@H]([C@H]1N)O[C@@H]2[C...,COC1=CC(=CC(=C1OC)OC)CC2=CN=C(N=C2N)N,CC1=CC(=NO1)NS(=O)(=O)C2=CC=C(C=C2)N,C1CC1N2C=C(C(=O)C3=CC(=C(C=C32)N4CCNCC4)F)C(=O)O,C[C@H]1COC2=C3N1C=C(C(=O)C3=CC(=C2N4CCN(CC4)C)...,COC1=C2C(=CC(=C1N3C[C@@H]4CCCN[C@@H]4C3)F)C(=O...
inchi,InChI=1S/C16H19N3O5S/c1-16(2)11(15(23)24)19-13...,InChI=1S/C23H27N5O7S/c1-4-26-10-11-27(19(32)18...,InChI=1S/C15H16N2O6S2/c1-15(2)9(14(22)23)17-11...,InChI=1S/C19H24N6O5S2/c1-25(5-3-4-6-25)7-10-8-...,InChI=1S/C14H14N8O4S3/c1-6-17-18-14(29-6)28-4-...,"InChI=1S/C23H30N12O8S2/c1-23(2,20(40)41)43-31-...",InChI=1S/C18H18N8O7S3/c1-25-18(22-12(28)13(29)...,"InChI=1S/C22H22N6O7S2/c1-22(2,20(33)34)35-26-1...","InChI=1S/C13H17N5O8S2/c1-5-7(10(20)18(5)28(23,...",InChI=1S/C12H17N3O4S/c1-6(16)9-7-4-8(20-3-2-14...,...,"InChI=1S/C3H7O4P/c1-2-3(7-2)8(4,5)6/h2-3H,1H3,...",InChI=1S/C22H43N5O13/c23-2-1-8(29)20(36)27-7-3...,InChI=1S/C18H37N5O9/c19-3-9-8(25)2-7(22)17(29-...,"InChI=1S/C21H39N7O12/c1-5-21(36,4-30)16(40-17-...",InChI=1S/C18H36N4O11/c19-2-6-10(25)12(27)13(28...,InChI=1S/C14H18N4O3/c1-19-10-5-8(6-11(20-2)12(...,InChI=1S/C10H11N3O3S/c1-7-6-10(12-16-7)13-17(1...,InChI=1S/C17H18FN3O3/c18-13-7-11-14(8-15(13)20...,InChI=1S/C18H20FN3O4/c1-10-9-26-17-14-11(16(23...,InChI=1S/C21H24FN3O4/c1-29-20-17-13(19(26)14(2...

In [8]:
compound_query.to_csv("../data/natural_antibiotics.csv")