---
This is metadata:

Kernel: chemoinformatics (Python 3.12.13)
Path:   /var/home/aeersriv/.anaconda3/envs/chemoinformaticschemoinformaticschemoinformatics/bin/python
---

# Ligand Preparation (Stage 0.1.4)

Prepare the ligand for molecular docking.

## Preliminaries

In [1]:
from os.path import abspath

import meeko
import molscrub
import pandas as pd
from rdkit import Chem

from src.utils.ligprep import LigPrep
from src.utils.logger import Logger
from src.utils.housekeeping import (
    fix_dir,
    log_pkg_ver,
    remove_prev_data
)

In [2]:
log = Logger("stage-0.1.4-ligand_prep")

INFO     Setup of logger complete, started <stage-0.1.4-ligand_prep> 2026-06-04 02:51:10.521689

In [3]:
pkg_imports: list[str] = ["meeko", "molscrub", "pandas", "rdkit"]
log_pkg_ver(pkg_imports, log)

INFO     Python v 3.10.20

INFO     Import meeko v 0.7.1

INFO     Import molscrub v 0.2.2

INFO     Import pandas v 2.3.3

INFO     Import rdkit v 2025.9.5

In [4]:
DIR: list[str] = [
        "../data/ligands/prepped",
        "../data/ligands/prepped/scrub",
        "../data/mirror_ligands/prepped",
        "../data/mirror_ligands/prepped/scrub"
    ]

In [5]:
remove_prev_data(DIR, log)

In [6]:
fix_dir(DIR, log)

INFO     ../data/ligands/prepped is missing, include to the list ...

INFO     ../data/ligands/prepped/scrub is missing, include to the list ...

INFO     ../data/mirror_ligands/prepped is missing, include to the list ...

INFO     ../data/mirror_ligands/prepped/scrub is missing, include to the list ...

INFO     Trying to create dir: ../data/ligands/prepped

INFO     Trying to create dir: ../data/ligands/prepped/scrub

INFO     Trying to create dir: ../data/mirror_ligands/prepped

INFO     Trying to create dir: ../data/mirror_ligands/prepped/scrub

In [7]:
CWD: str = abspath(".")
MIR_DIR: str = f"{CWD}/../data/mirror_ligands/prepped"
NAT_DIR: str = f"{CWD}/../data/ligands/prepped"

## Data

In [8]:
native = pd.read_csv(
        f"../data//natural_antibiotics.csv", index_col=0
    )
mirror = pd.read_csv(f"../data/mirror_ligand.csv", index_col=0)

In [9]:
native.head()

,Amoxicillin,Piperacillin,Ticarcillin,Cefepime,Cefazolin,Ceftolozane,Ceftriaxone,Ceftazidime,Aztreonam,Imipenem,...,Fosfomycin,Amikacin,Tobramycin,Streptomycin,Kanamycin,Trimethoprim,Sulfamethoxazole,Ciprofloxacin,Levofloxacin,Moxifloxacin
cid,33613,43672,36921,5479537,33255,53234134,5479530,5481173,5742832,104838,...,446987,37768,36294,19649,6032,5578,5329,2764,149096,152946
smiles,CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H]...,CCN1CCN(C(=O)C1=O)C(=O)N[C@H](C2=CC=CC=C2)C(=O...,CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H]...,C[N+]1(CCCC1)CC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)...,CC1=NN=C(S1)SCC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)...,CC(C)(C(=O)O)O/N=C(/C1=NSC(=N1)N)\C(=O)N[C@H]2...,CN1C(=NC(=O)C(=O)N1)SCC2=C(N3[C@@H]([C@@H](C3=...,CC(C)(C(=O)O)O/N=C(/C1=CSC(=N1)N)\C(=O)N[C@H]2...,C[C@H]1[C@@H](C(=O)N1S(=O)(=O)O)NC(=O)/C(=N\OC...,C[C@H]([C@@H]1[C@H]2CC(=C(N2C1=O)C(=O)O)SCCN=CN)O,...,C[C@H]1[C@H](O1)P(=O)(O)O,C1[C@@H]([C@H]([C@@H]([C@H]([C@@H]1NC(=O)[C@H]...,C1[C@@H]([C@H]([C@@H]([C@H]([C@@H]1N)O[C@@H]2[...,C[C@H]1[C@@]([C@H]([C@@H](O1)O[C@@H]2[C@H]([C@...,C1[C@H]([C@@H]([C@H]([C@@H]([C@H]1N)O[C@@H]2[C...,COC1=CC(=CC(=C1OC)OC)CC2=CN=C(N=C2N)N,CC1=CC(=NO1)NS(=O)(=O)C2=CC=C(C=C2)N,C1CC1N2C=C(C(=O)C3=CC(=C(C=C32)N4CCNCC4)F)C(=O)O,C[C@H]1COC2=C3N1C=C(C(=O)C3=CC(=C2N4CCN(CC4)C)...,COC1=C2C(=CC(=C1N3C[C@@H]4CCCN[C@@H]4C3)F)C(=O...
inchi,InChI=1S/C16H19N3O5S/c1-16(2)11(15(23)24)19-13...,InChI=1S/C23H27N5O7S/c1-4-26-10-11-27(19(32)18...,InChI=1S/C15H16N2O6S2/c1-15(2)9(14(22)23)17-11...,InChI=1S/C19H24N6O5S2/c1-25(5-3-4-6-25)7-10-8-...,InChI=1S/C14H14N8O4S3/c1-6-17-18-14(29-6)28-4-...,"InChI=1S/C23H30N12O8S2/c1-23(2,20(40)41)43-31-...",InChI=1S/C18H18N8O7S3/c1-25-18(22-12(28)13(29)...,"InChI=1S/C22H22N6O7S2/c1-22(2,20(33)34)35-26-1...","InChI=1S/C13H17N5O8S2/c1-5-7(10(20)18(5)28(23,...",InChI=1S/C12H17N3O4S/c1-6(16)9-7-4-8(20-3-2-14...,...,"InChI=1S/C3H7O4P/c1-2-3(7-2)8(4,5)6/h2-3H,1H3,...",InChI=1S/C22H43N5O13/c23-2-1-8(29)20(36)27-7-3...,InChI=1S/C18H37N5O9/c19-3-9-8(25)2-7(22)17(29-...,"InChI=1S/C21H39N7O12/c1-5-21(36,4-30)16(40-17-...",InChI=1S/C18H36N4O11/c19-2-6-10(25)12(27)13(28...,InChI=1S/C14H18N4O3/c1-19-10-5-8(6-11(20-2)12(...,InChI=1S/C10H11N3O3S/c1-7-6-10(12-16-7)13-17(1...,InChI=1S/C17H18FN3O3/c18-13-7-11-14(8-15(13)20...,InChI=1S/C18H20FN3O4/c1-10-9-26-17-14-11(16(23...,InChI=1S/C21H24FN3O4/c1-29-20-17-13(19(26)14(2...

In [10]:
mirror.head()

,Amoxicillin,Piperacillin,Ticarcillin,Cefepime,Cefazolin,Ceftolozane,Ceftriaxone,Ceftazidime,Aztreonam,Imipenem,...,Fosfomycin,Amikacin,Tobramycin,Streptomycin,Kanamycin,Trimethoprim,Sulfamethoxazole,Ciprofloxacin,Levofloxacin,Moxifloxacin
cid,33613,43672,36921,5479537,33255,53234134,5479530,5481173,5742832,104838,...,446987,37768,36294,19649,6032,5578,5329,2764,149096,152946
smiles,CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H]...,CCN1CCN(C(=O)C1=O)C(=O)N[C@H](C2=CC=CC=C2)C(=O...,CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H]...,C[N+]1(CCCC1)CC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)...,CC1=NN=C(S1)SCC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)...,CC(C)(C(=O)O)O/N=C(/C1=NSC(=N1)N)\C(=O)N[C@H]2...,CN1C(=NC(=O)C(=O)N1)SCC2=C(N3[C@@H]([C@@H](C3=...,CC(C)(C(=O)O)O/N=C(/C1=CSC(=N1)N)\C(=O)N[C@H]2...,C[C@H]1[C@@H](C(=O)N1S(=O)(=O)O)NC(=O)/C(=N\OC...,C[C@H]([C@@H]1[C@H]2CC(=C(N2C1=O)C(=O)O)SCCN=CN)O,...,C[C@H]1[C@H](O1)P(=O)(O)O,C1[C@@H]([C@H]([C@@H]([C@H]([C@@H]1NC(=O)[C@H]...,C1[C@@H]([C@H]([C@@H]([C@H]([C@@H]1N)O[C@@H]2[...,C[C@H]1[C@@]([C@H]([C@@H](O1)O[C@@H]2[C@H]([C@...,C1[C@H]([C@@H]([C@H]([C@@H]([C@H]1N)O[C@@H]2[C...,COC1=CC(=CC(=C1OC)OC)CC2=CN=C(N=C2N)N,CC1=CC(=NO1)NS(=O)(=O)C2=CC=C(C=C2)N,C1CC1N2C=C(C(=O)C3=CC(=C(C=C32)N4CCNCC4)F)C(=O)O,C[C@H]1COC2=C3N1C=C(C(=O)C3=CC(=C2N4CCN(CC4)C)...,COC1=C2C(=CC(=C1N3C[C@@H]4CCCN[C@@H]4C3)F)C(=O...
inchi,InChI=1S/C16H19N3O5S/c1-16(2)11(15(23)24)19-13...,InChI=1S/C23H27N5O7S/c1-4-26-10-11-27(19(32)18...,InChI=1S/C15H16N2O6S2/c1-15(2)9(14(22)23)17-11...,InChI=1S/C19H24N6O5S2/c1-25(5-3-4-6-25)7-10-8-...,InChI=1S/C14H14N8O4S3/c1-6-17-18-14(29-6)28-4-...,"InChI=1S/C23H30N12O8S2/c1-23(2,20(40)41)43-31-...",InChI=1S/C18H18N8O7S3/c1-25-18(22-12(28)13(29)...,"InChI=1S/C22H22N6O7S2/c1-22(2,20(33)34)35-26-1...","InChI=1S/C13H17N5O8S2/c1-5-7(10(20)18(5)28(23,...",InChI=1S/C12H17N3O4S/c1-6(16)9-7-4-8(20-3-2-14...,...,"InChI=1S/C3H7O4P/c1-2-3(7-2)8(4,5)6/h2-3H,1H3,...",InChI=1S/C22H43N5O13/c23-2-1-8(29)20(36)27-7-3...,InChI=1S/C18H37N5O9/c19-3-9-8(25)2-7(22)17(29-...,"InChI=1S/C21H39N7O12/c1-5-21(36,4-30)16(40-17-...",InChI=1S/C18H36N4O11/c19-2-6-10(25)12(27)13(28...,InChI=1S/C14H18N4O3/c1-19-10-5-8(6-11(20-2)12(...,InChI=1S/C10H11N3O3S/c1-7-6-10(12-16-7)13-17(1...,InChI=1S/C17H18FN3O3/c18-13-7-11-14(8-15(13)20...,InChI=1S/C18H20FN3O4/c1-10-9-26-17-14-11(16(23...,InChI=1S/C21H24FN3O4/c1-29-20-17-13(19(26)14(2...
mirror_smi,CC1(C)S[C@H]2[C@@H](NC(=O)[C@@H](N)c3ccc(O)cc3...,CCN1CCN(C(=O)N[C@H](C(=O)N[C@H]2C(=O)N3[C@H]2S...,CC1(C)S[C@H]2[C@@H](NC(=O)[C@@H](C(=O)O)c3ccsc...,CO/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)[O-])=C(C[N+...,Cc1nnc(SCC2=C(C(=O)O)N3C(=O)[C@H](NC(=O)Cn4cnn...,Cn1c(N)c(NC(=O)NCCN)c[n+]1CC1=C(C(=O)[O-])N2C(...,CO/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)O)=C(CSc3nc(...,CC(C)(O/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)[O-])=C...,C[C@@H]1[C@@H](NC(=O)/C(=N\OC(C)(C)C(=O)O)c2cs...,C[C@H](O)[C@@H]1C(=O)N2C(C(=O)O)=C(SCCN=CN)C[C...,...,C[C@H]1O[C@H]1P(=O)(O)O,NCC[C@@H](O)C(=O)N[C@H]1C[C@@H](N)[C@H](O[C@@H...,NC[C@@H]1O[C@@H](O[C@@H]2[C@@H](O)[C@H](O[C@@H...,CN[C@H]1[C@@H](O[C@@H]2[C@@H](O[C@@H]3[C@@H](O...,NC[C@@H]1O[C@@H](O[C@@H]2[C@@H](O)[C@H](O[C@@H...,COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC,Cc1cc(NS(=O)(=O)c2ccc(N)cc2)no1,O=C(O)c1cn(C2CC2)c2cc(N3CCNCC3)c(F)cc2c1=O,C[C@@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O...,COc1c(N2C[C@H]3CCCN[C@H]3C2)c(F)cc2c(=O)c(C(=O...

## Ligand Preparation

In [11]:
ligprep: LigPrep = LigPrep(log)

In [12]:
prepped_mir: list[str] = []
prepped_nat: list[str] = []

for nat, mir in zip(native, mirror):
    nat_prep: str | None = ligprep.ligand_prep(
            native[nat]["smiles"],
            f"Native-{native[nat]['cid']}",
            NAT_DIR
        )
    mir_prep: str | None = ligprep.ligand_prep(
            mirror[mir]["mirror_smi"],
            f"Mirror-{mirror[mir]['cid']}",
            MIR_DIR
        )

    if nat_prep:
        prepped_nat.append(nat_prep)

    if mir_prep:
        prepped_mir.append(mir_prep)

INFO     Scrubing Native-33613 with scrub.py
         CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H](C3=CC=C(C=C3)O)N)C(=O)O)C -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-33613-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-33613 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-33613-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-33613-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-33613 with scrub.py CC1(C)S[C@H]2[C@@H](NC(=O)[C@@H](N)c3ccc(O)cc3)C(=O)N2[C@@H]1C(=O)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-33613-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-33613 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-33613-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-33613-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-43672 with scrub.py
         CCN1CCN(C(=O)C1=O)C(=O)N[C@H](C2=CC=CC=C2)C(=O)N[C@H]3[C@@H]4N(C3=O)[C@H](C(S4)(C)C)C(=O)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-43672-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-43672 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-43672-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-43672-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-43672 with scrub.py
         CCN1CCN(C(=O)N[C@H](C(=O)N[C@H]2C(=O)N3[C@H]2SC(C)(C)[C@H]3C(=O)O)c2ccccc2)C(=O)C1=O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-43672-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-43672 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-43672-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-43672-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-36921 with scrub.py
         CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H](C3=CSC=C3)C(=O)O)C(=O)O)C -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-36921-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-36921 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-36921-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-36921-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-36921 with scrub.py CC1(C)S[C@H]2[C@@H](NC(=O)[C@@H](C(=O)O)c3ccsc3)C(=O)N2[C@@H]1C(=O)O
         -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-36921-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-36921 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-36921-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-36921-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-5479537 with scrub.py
         C[N+]1(CCCC1)CC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)/C(=N\OC)/C4=CSC(=N4)N)SC2)C(=O)[O-] -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-5479537-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-5479537 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-5479537-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-5479537-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-5479537 with scrub.py
         CO/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)[O-])=C(C[N+]3(C)CCCC3)CS[C@@H]12)c1csc(N)n1 -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-5479537-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-5479537 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-5479537-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-5479537-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-33255 with scrub.py CC1=NN=C(S1)SCC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)CN4C=NN=N4)SC2)C(=O)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-33255-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-33255 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-33255-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-33255-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-33255 with scrub.py Cc1nnc(SCC2=C(C(=O)O)N3C(=O)[C@H](NC(=O)Cn4cnnn4)[C@@H]3SC2)s1 -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-33255-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-33255 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-33255-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-33255-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-53234134 with scrub.py
         CC(C)(C(=O)O)O/N=C(/C1=NSC(=N1)N)\C(=O)N[C@H]2[C@@H]3N(C2=O)C(=C(CS3)C[N+]4=CC(=C(N4C)N)NC(=O)NCCN)C(=O)[O
         -] -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-53234134-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-53234134 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-53234134-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-53234134-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-53234134 with scrub.py
         Cn1c(N)c(NC(=O)NCCN)c[n+]1CC1=C(C(=O)[O-])N2C(=O)[C@H](NC(=O)/C(=N\OC(C)(C)C(=O)O)c3nsc(N)n3)[C@@H]2SC1 -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-53234134-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-53234134 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-53234134-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-53234134-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-5479530 with scrub.py
         CN1C(=NC(=O)C(=O)N1)SCC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)/C(=N\OC)/C4=CSC(=N4)N)SC2)C(=O)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-5479530-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-5479530 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-5479530-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-5479530-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-5479530 with scrub.py
         CO/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)O)=C(CSc3nc(=O)c(=O)[nH]n3C)CS[C@@H]12)c1csc(N)n1 -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-5479530-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-5479530 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-5479530-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-5479530-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-5481173 with scrub.py
         CC(C)(C(=O)O)O/N=C(/C1=CSC(=N1)N)\C(=O)N[C@H]2[C@@H]3N(C2=O)C(=C(CS3)C[N+]4=CC=CC=C4)C(=O)[O-] -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-5481173-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-5481173 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-5481173-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-5481173-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-5481173 with scrub.py
         CC(C)(O/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)[O-])=C(C[n+]3ccccc3)CS[C@@H]12)c1csc(N)n1)C(=O)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-5481173-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-5481173 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-5481173-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-5481173-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-5742832 with scrub.py
         C[C@H]1[C@@H](C(=O)N1S(=O)(=O)O)NC(=O)/C(=N\OC(C)(C)C(=O)O)/C2=CSC(=N2)N -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-5742832-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-5742832 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-5742832-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-5742832-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-5742832 with scrub.py
         C[C@@H]1[C@@H](NC(=O)/C(=N\OC(C)(C)C(=O)O)c2csc(N)n2)C(=O)N1S(=O)(=O)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-5742832-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-5742832 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-5742832-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-5742832-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-104838 with scrub.py C[C@H]([C@@H]1[C@H]2CC(=C(N2C1=O)C(=O)O)SCCN=CN)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-104838-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-104838 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-104838-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-104838-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-104838 with scrub.py C[C@H](O)[C@@H]1C(=O)N2C(C(=O)O)=C(SCCN=CN)C[C@@H]12 -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-104838-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-104838 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-104838-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-104838-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-441130 with scrub.py
         C[C@@H]1[C@@H]2[C@H](C(=O)N2C(=C1S[C@H]3C[C@H](NC3)C(=O)N(C)C)C(=O)O)[C@@H](C)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-441130-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-441130 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-441130-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-441130-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-441130 with scrub.py
         C[C@H](O)[C@@H]1C(=O)N2C(C(=O)O)=C(S[C@H]3CN[C@@H](C(=O)N(C)C)C3)[C@@H](C)[C@@H]12 -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-441130-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-441130 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-441130-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-441130-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-73303 with scrub.py
         C[C@@H]1[C@@H]2[C@H](C(=O)N2C(=C1S[C@H]3C[C@H](NC3)CNS(=O)(=O)N)C(=O)O)[C@@H](C)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-73303-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-73303 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-73303-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-73303-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-73303 with scrub.py
         C[C@H](O)[C@@H]1C(=O)N2C(C(=O)O)=C(S[C@H]3CN[C@@H](CNS(N)(=O)=O)C3)[C@@H](C)[C@@H]12 -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-73303-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-73303 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-73303-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-73303-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-14969 with scrub.py
         C[C@H]1[C@H]([C@@](C[C@@H](O1)O[C@@H]2[C@H]([C@@H]([C@H](O[C@H]2OC3=C4C=C5C=C3OC6=C(C=C(C=C6)[C@H]([C@H](C
         (=O)N[C@H](C(=O)N[C@H]5C(=O)N[C@@H]7C8=CC(=C(C=C8)O)C9=C(C=C(C=C9O)O)[C@H](NC(=O)[C@H]([C@@H](C1=CC(=C(O4)
         C=C1)Cl)O)NC7=O)C(=O)O)CC(=O)N)NC(=O)[C@@H](CC(C)C)NC)O)Cl)CO)O)O)(C)N)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-14969-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-14969 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-14969-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-14969-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-14969 with scrub.py
         CN[C@@H](CC(C)C)C(=O)N[C@@H]1C(=O)N[C@H](CC(N)=O)C(=O)N[C@@H]2C(=O)N[C@@H]3C(=O)N[C@@H](C(=O)N[C@@H](C(=O)
         O)c4cc(O)cc(O)c4-c4cc3ccc4O)[C@@H](O)c3ccc(c(Cl)c3)Oc3cc2cc(c3O[C@H]2O[C@@H](CO)[C@H](O)[C@@H](O)[C@@H]2O[
         C@@H]2C[C@@](C)(N)[C@@H](O)[C@@H](C)O2)Oc2ccc(cc2Cl)[C@@H]1O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-14969-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-14969 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-14969-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-14969-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-54686904 with scrub.py
         CC(C)(C)NCC(=O)NC1=CC(=C2C[C@H]3C[C@H]4[C@@H](C(=O)C(=C([C@]4(C(=O)C3=C(C2=C1O)O)O)O)C(=O)N)N(C)C)N(C)C -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-54686904-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-54686904 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-54686904-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-54686904-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-54686904 with scrub.py
         CN(C)c1cc(NC(=O)CNC(C)(C)C)c(O)c2c1C[C@@H]1C[C@@H]3[C@@H](N(C)C)C(=O)C(C(N)=O)=C(O)[C@]3(O)C(=O)C1=C2O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-54686904-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-54686904 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-54686904-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-54686904-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-54675783 with scrub.py
         CN(C)[C@H]1[C@@H]2C[C@@H]3CC4=C(C=CC(=C4C(=C3C(=O)[C@@]2(C(=C(C1=O)C(=O)N)O)O)O)O)N(C)C -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-54675783-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-54675783 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-54675783-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-54675783-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-54675783 with scrub.py
         CN(C)c1ccc(O)c2c1C[C@@H]1C[C@@H]3[C@@H](N(C)C)C(=O)C(C(N)=O)=C(O)[C@]3(O)C(=O)C1=C2O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-54675783-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-54675783 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-54675783-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-54675783-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-54671203 with scrub.py
         C[C@@H]1[C@H]2[C@@H]([C@H]3[C@@H](C(=O)C(=C([C@]3(C(=O)C2=C(C4=C1C=CC=C4O)O)O)O)C(=O)N)N(C)C)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-54671203-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-54671203 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-54671203-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-54671203-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-54671203 with scrub.py
         C[C@@H]1c2cccc(O)c2C(O)=C2C(=O)[C@@]3(O)C(O)=C(C(N)=O)C(=O)[C@H](N(C)C)[C@H]3[C@H](O)[C@H]21 -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-54671203-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-54671203 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-54671203-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-54671203-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-54675776 with scrub.py
         C[C@@]1([C@H]2C[C@H]3[C@@H](C(=O)C(=C([C@]3(C(=O)C2=C(C4=C1C=CC=C4O)O)O)O)C(=O)N)N(C)C)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-54675776-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-54675776 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-54675776-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-54675776-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-54675776 with scrub.py
         CN(C)[C@H]1C(=O)C(C(N)=O)=C(O)[C@]2(O)C(=O)C3=C(O)c4c(O)cccc4[C@](C)(O)[C@@H]3C[C@H]12 -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-54675776-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-54675776 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-54675776-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-54675776-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-54675777 with scrub.py
         C[C@@]1([C@H]2C[C@H]3[C@@H](C(=O)C(=C([C@]3(C(=O)C2=C(C4=C(C=CC(=C41)Cl)O)O)O)O)C(=O)N)N(C)C)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-54675777-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-54675777 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-54675777-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-54675777-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-54675777 with scrub.py
         CN(C)[C@H]1C(=O)C(C(N)=O)=C(O)[C@]2(O)C(=O)C3=C(O)c4c(O)ccc(Cl)c4[C@](C)(O)[C@@H]3C[C@H]12 -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-54675777-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-54675777 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-54675777-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-54675777-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-447043 with scrub.py
         CC[C@@H]1[C@@]([C@@H]([C@H](N(C[C@@H](C[C@@]([C@@H]([C@H]([C@@H]([C@H](C(=O)O1)C)O[C@H]2C[C@@]([C@H]([C@@H
         ](O2)C)O)(C)OC)C)O[C@H]3[C@@H]([C@H](C[C@H](O3)C)N(C)C)O)(C)O)C)C)C)O)(C)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-447043-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-447043 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-447043-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-447043-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-447043 with scrub.py
         CC[C@@H]1OC(=O)[C@@H](C)[C@H](O[C@@H]2C[C@](C)(OC)[C@H](O)[C@@H](C)O2)[C@@H](C)[C@H](O[C@H]2O[C@@H](C)C[C@
         @H](N(C)C)[C@@H]2O)[C@@](C)(O)C[C@H](C)CN(C)[C@@H](C)[C@H](O)[C@@]1(C)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-447043-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-447043 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-447043-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-447043-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-12560 with scrub.py
         CC[C@@H]1[C@@]([C@@H]([C@H](C(=O)[C@@H](C[C@@]([C@@H]([C@H]([C@@H]([C@H](C(=O)O1)C)O[C@H]2C[C@@]([C@H]([C@
         @H](O2)C)O)(C)OC)C)O[C@H]3[C@@H]([C@H](C[C@H](O3)C)N(C)C)O)(C)O)C)C)O)(C)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-12560-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-12560 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-12560-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-12560-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-12560 with scrub.py
         CC[C@@H]1OC(=O)[C@@H](C)[C@H](O[C@@H]2C[C@](C)(OC)[C@H](O)[C@@H](C)O2)[C@@H](C)[C@H](O[C@H]2O[C@@H](C)C[C@
         @H](N(C)C)[C@@H]2O)[C@@](C)(O)C[C@H](C)C(=O)[C@@H](C)[C@H](O)[C@@]1(C)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-12560-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-12560 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-12560-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-12560-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-84029 with scrub.py
         CC[C@@H]1[C@@]([C@@H]([C@H](C(=O)[C@@H](C[C@@]([C@@H]([C@H]([C@@H]([C@H](C(=O)O1)C)O[C@H]2C[C@@]([C@H]([C@
         @H](O2)C)O)(C)OC)C)O[C@H]3[C@@H]([C@H](C[C@H](O3)C)N(C)C)O)(C)OC)C)C)O)(C)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-84029-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-84029 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-84029-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-84029-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-84029 with scrub.py
         CC[C@@H]1OC(=O)[C@@H](C)[C@H](O[C@@H]2C[C@](C)(OC)[C@H](O)[C@@H](C)O2)[C@@H](C)[C@H](O[C@H]2O[C@@H](C)C[C@
         @H](N(C)C)[C@@H]2O)[C@@](C)(OC)C[C@H](C)C(=O)[C@@H](C)[C@H](O)[C@@]1(C)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-84029-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-84029 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-84029-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-84029-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-5959 with scrub.py C1=CC(=CC=C1[C@H]([C@@H](CO)NC(=O)C(Cl)Cl)O)[N+](=O)[O-] -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-5959-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-5959 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-5959-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-5959-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-5959 with scrub.py O=C(N[C@@H](CO)[C@@H](O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-5959-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-5959 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-5959-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-5959-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-441401 with scrub.py CC(=O)NC[C@H]1CN(C(=O)O1)C2=CC(=C(C=C2)N3CCOCC3)F -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-441401-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-441401 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-441401-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-441401-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-441401 with scrub.py CC(=O)NC[C@@H]1CN(c2ccc(N3CCOCC3)c(F)c2)C(=O)O1 -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-441401-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-441401 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-441401-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-441401-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-135398735 with scrub.py
         C[C@H]1/C=C/C=C(\C(=O)NC2=C(C(=C3C(=C2O)C(=C(C4=C3C(=O)[C@](O4)(O/C=C/[C@@H]([C@H]([C@H]([C@@H]([C@@H]([C@
         @H]([C@H]1O)C)O)C)OC(=O)C)C)OC)C)C)O)O)/C=N/N5CCN(CC5)C)/C -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-135398735-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-135398735 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-135398735-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-135398735-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-135398735 with scrub.py
         CO[C@@H]1/C=C/O[C@]2(C)Oc3c(C)c(O)c4c(O)c(c(/C=N/N5CCN(C)CC5)c(O)c4c3C2=O)NC(=O)/C(C)=C\C=C\[C@@H](C)[C@@H
         ](O)[C@H](C)[C@H](O)[C@H](C)[C@@H](OC(C)=O)[C@H]1C -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-135398735-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-135398735 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-135398735-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-135398735-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-446987 with scrub.py C[C@H]1[C@H](O1)P(=O)(O)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-446987-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-446987 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-446987-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-446987-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-446987 with scrub.py C[C@H]1O[C@H]1P(=O)(O)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-446987-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-446987 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-446987-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-446987-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-37768 with scrub.py
         C1[C@@H]([C@H]([C@@H]([C@H]([C@@H]1NC(=O)[C@H](CCN)O)O[C@@H]2[C@@H]([C@H]([C@@H]([C@H](O2)CO)O)N)O)O)O[C@@
         H]3[C@@H]([C@H]([C@@H]([C@H](O3)CN)O)O)O)N -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-37768-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-37768 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-37768-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-37768-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-37768 with scrub.py
         NCC[C@@H](O)C(=O)N[C@H]1C[C@@H](N)[C@H](O[C@@H]2O[C@@H](CN)[C@H](O)[C@@H](O)[C@@H]2O)[C@@H](O)[C@@H]1O[C@@
         H]1O[C@@H](CO)[C@H](O)[C@@H](N)[C@@H]1O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-37768-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-37768 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-37768-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-37768-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-36294 with scrub.py
         C1[C@@H]([C@H]([C@@H]([C@H]([C@@H]1N)O[C@@H]2[C@@H]([C@H]([C@@H]([C@H](O2)CO)O)N)O)O)O[C@@H]3[C@@H](C[C@@H
         ]([C@H](O3)CN)O)N)N -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-36294-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-36294 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-36294-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-36294-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-36294 with scrub.py
         NC[C@@H]1O[C@@H](O[C@@H]2[C@@H](O)[C@H](O[C@@H]3O[C@@H](CO)[C@H](O)[C@@H](N)[C@@H]3O)[C@@H](N)C[C@H]2N)[C@
         @H](N)C[C@H]1O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-36294-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-36294 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-36294-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-36294-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-19649 with scrub.py
         C[C@H]1[C@@]([C@H]([C@@H](O1)O[C@@H]2[C@H]([C@@H]([C@H]([C@@H]([C@H]2O)O)N=C(N)N)O)N=C(N)N)O[C@H]3[C@H]([C
         @@H]([C@H]([C@@H](O3)CO)O)O)NC)(C=O)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-19649-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-19649 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-19649-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-19649-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-19649 with scrub.py
         CN[C@H]1[C@@H](O[C@@H]2[C@@H](O[C@@H]3[C@@H](O)[C@H](O)[C@@H](N=C(N)N)[C@H](O)[C@H]3N=C(N)N)O[C@H](C)[C@@]
         2(O)C=O)O[C@H](CO)[C@@H](O)[C@@H]1O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-19649-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-19649 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-19649-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-19649-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-6032 with scrub.py
         C1[C@H]([C@@H]([C@H]([C@@H]([C@H]1N)O[C@@H]2[C@@H]([C@H]([C@@H]([C@H](O2)CN)O)O)O)O)O[C@@H]3[C@@H]([C@H]([
         C@@H]([C@H](O3)CO)O)N)O)N -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-6032-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-6032 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-6032-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-6032-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-6032 with scrub.py
         NC[C@@H]1O[C@@H](O[C@@H]2[C@@H](O)[C@H](O[C@@H]3O[C@@H](CO)[C@H](O)[C@@H](N)[C@@H]3O)[C@@H](N)C[C@H]2N)[C@
         @H](O)[C@H](O)[C@H]1O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-6032-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-6032 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-6032-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-6032-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-5578 with scrub.py COC1=CC(=CC(=C1OC)OC)CC2=CN=C(N=C2N)N -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-5578-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-5578 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-5578-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-5578-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-5578 with scrub.py COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-5578-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-5578 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-5578-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-5578-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-5329 with scrub.py CC1=CC(=NO1)NS(=O)(=O)C2=CC=C(C=C2)N -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-5329-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-5329 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-5329-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-5329-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-5329 with scrub.py Cc1cc(NS(=O)(=O)c2ccc(N)cc2)no1 -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-5329-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-5329 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-5329-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-5329-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-2764 with scrub.py C1CC1N2C=C(C(=O)C3=CC(=C(C=C32)N4CCNCC4)F)C(=O)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-2764-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-2764 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-2764-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-2764-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-2764 with scrub.py O=C(O)c1cn(C2CC2)c2cc(N3CCNCC3)c(F)cc2c1=O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-2764-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-2764 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-2764-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-2764-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-149096 with scrub.py C[C@H]1COC2=C3N1C=C(C(=O)C3=CC(=C2N4CCN(CC4)C)F)C(=O)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-149096-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-149096 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-149096-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-149096-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-149096 with scrub.py C[C@@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23 -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-149096-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-149096 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-149096-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-149096-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Native-152946 with scrub.py COC1=C2C(=CC(=C1N3C[C@@H]4CCCN[C@@H]4C3)F)C(=O)C(=CN2C5CC5)C(=O)O -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-152946-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Native-152946 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/scrub/Native-152946-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         ligands/prepped/Native-152946-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

INFO     Scrubing Mirror-152946 with scrub.py COc1c(N2C[C@H]3CCCN[C@H]3C2)c(F)cc2c(=O)c(C(=O)O)cn(C3CC3)c12 -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-152946-scrub.sdf --ph 7.4 --skip_tautomer

Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)

INFO     Running mk_prepapre_ligand.py on Mirror-152946 with mk_prepare_ligand.py -i
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/scrub/Mirror-152946-scrub.sdf -o
         /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/
         mirror_ligands/prepped/Mirror-152946-prepped.pdbqt

Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0

In [13]:
print(
    f"Prepared native ligands: {len(prepped_nat)}\n"
    f"Prepared mirror ligands: {len(prepped_mir)}\n"
)

Prepared native ligands: 34
Prepared mirror ligands: 34